momentum-mod/game

- sp/src/game/server/momentum/server_events.cpp
- sp/src/game/shared/momentum/mom_player_shared.cpp
- sp/src/game/shared/movevars_shared.cpp
AirAccelerate now changes automatically based on MOMGM.
AirAccelerate is no longer a hidden cvar. It will be hidden again during beta (?).
Added preliminary support for kz/scroll game modes.
Removed _DEBUG issues causing crashing and compiler errors if project is compiled on debug.
> AirAccelerate support

- mp/src/game/server/cbase.cpp
- mp/src/game/server/eventqueue.h
Reopened from #85. I previously added a separate tick count inside CEventQueue since gpGlobals->tickcount isn't consistent on CS:S at all, but it seems to be fine here, so I've removed that.
The only change now is a switch from using curtime to tickcount since using curtime suffers from floating-point precision errors.
The only boosters that don't seem to work now are the touch-activated kinds used in bhop_null and bhop_null_fix. There's no neat, general way to fix those in the engine code -- there would need to be branches for specific triggers in those specific maps, which is awkward and seems more appropriately solved by something like a Stripper config or a new map with the changes.
> Fix boosters

- mp/game/momentum/cfg/valve.rc
- mp/src/game/client/cdll_client_int.cpp
Also added in BenLubar's fix for server time during demo timescale, because why not. It doesn't do anything for us other than fix the server time going out of sync, but that might be useful for .... something... ... later....
> For real this time, fix demo veiw interpolation and timescale cattywampus-ness

- mp/src/game/shared/momentum/mom_gamemovement.cpp
- mp/src/gameui/OptionsSubAudio.cpp
- mp/src/gameui/OptionsSubAudio.h
- mp/src/vgui2/vgui_controls/Label.cpp
- mp/src/vgui2/vgui_controls/Panel.cpp
* CUtlStrings should check IsEmpty for null strings, fixes crashes with the menu
* Re-added "mute audio when game loses focus" to audio settings
* Fixed sliding along stairs/slight inclines, TBD if this causes any other regressions though
> Small bugfixes

- mp/src/game/client/client_momentum.vpc
- mp/src/game/client/momentum/ui/CMomImagePanel.cpp
- mp/src/game/client/momentum/ui/CMomImagePanel.h
- mp/src/public/stb/image/stb_image.h
- mp/src/thirdparty/stb/image/stb_image.h
We can bypass VTF/VMT creation for rendering JPG/PNG/GIF/BMP/TGAs
directly
Currently only renders as big as the panel is. If we need offsets we can always add them
Shoutouts to the contributors that made stb_image, a public domain image
processor for C/C++
> Add a panel that renders images directly

- mp/src/game/server/momentum/mapzones_edit.cpp
ATM zones created through zone builder can't be used since clients don't pass the trigger filter and `OnStartTouch` is never called. Just adds the spawn flag to fix this.
> Fix zone trigger filter

- mp/game/momentum/resource/ui/SettingsPanel_HudSettings.res
- mp/src/game/client/momentum/ui/HUD/hud_keypress.cpp
- mp/src/game/client/momentum/ui/HUD/hud_mapinfo.cpp
- mp/src/game/client/momentum/ui/HUD/hud_speedometer.cpp
- mp/src/game/client/momentum/ui/HUD/hud_strafesync.cpp
- mp/src/game/client/momentum/ui/HUD/hud_timer.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/HudSettingsPage.cpp
HUD convars were sometimes prefixed, sometimes not. _hud_ should be prepended to all convars so that they dont clutter the global console namespace or even the mom console command namespace.
I'm not sure of the macros are a good idea since the ConVar name might get too verbose and you just want a simpler name for the static var
> HUD Convar Namespacing

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_player.h
- mp/src/game/server/momentum/mom_replay_entity.cpp
- mp/src/game/server/momentum/mom_replay_entity.h
- mp/src/game/server/momentum/mom_replay_system.cpp
- mp/src/game/server/momentum/mom_replay_system.h
- mp/src/game/shared/momentum/run/mom_replay_data.h
This does NOT fix jerkiness when ping > 0, AFAIK for that you need to predict the replay on the client.
Keeps compatibility with previous replays.
> Fix teleports being interpolated in replays

- mp/src/game/server/momentum/mom_lobby_system.cpp
The CUtlBuffer class automatically grows as needed and does not need to reserve this much memory for how small the packets are.
Alternatively, rework how the packet base class works so it can be used bidirectionally where the size is always known beforehand.
> Don't reserve big memory buffer for packets

- .circleci/config.yml
- mp/src/devtools/makefile_base_posix.mak
- mp/src/game/client/clientshadowmgr.cpp
- mp/src/game/client/momentum/mom_map_cache.cpp
- mp/src/game/client/momentum/mom_run_poster.cpp
- mp/src/game/client/momentum/ui/leaderboards/LeaderboardsTimes.cpp
- mp/src/game/server/momentum/mom_lobby_system.cpp
- mp/src/game/shared/momentum/util/jsontokv.cpp
- mp/src/game/shared/momentum/util/mom_util.cpp
Which means we update from GCC 4.6 to 4.8, which allows us to use the `override` keyword and constructors within the same class, to name a few...
See the [Linux compile instructions](https://github.com/momentum-mod/game/wiki/Building-The-Game#linux) for the new workflow setup.
Closes #260
> Update Linux Workflow to Steam Runtime Chroot

- mp/game/momentum/resource/LeaderboardsScheme.res
- mp/game/momentum/resource/ui/Spectator.res
- mp/src/game/client/momentum/mom_api_models.cpp
- mp/src/game/client/momentum/mom_map_cache.cpp
- mp/src/game/client/momentum/ui/leaderboards/LeaderboardsTimes.cpp
- mp/src/game/client/momentum/ui/leaderboards/LeaderboardsTimes.h
- mp/src/game/client/momentum/ui/spectate/mom_spectator_gui.cpp
- mp/src/game/client/momentum/ui/spectate/mom_spectator_gui.h
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_triggers.cpp
- mp/src/game/server/momentum/tickset.cpp
- mp/src/game/shared/momentum/util/mom_util.cpp
- mp/src/public/vgui_controls/SectionedListPanel.h
- mp/src/vgui2/vgui_controls/SectionedListPanel.cpp
Last merge from this branch, as we're moving to an individual card-per-branch workflow.
Outline to local player's time on the leaderboards
Capped sv_interval_per_tick to the engine max and minimum
Do not limit player speed if using a saveloc out of the start zone
Versioned the map-cache.dat file so any game updates force it to refresh
Fixed player spectate state not resetting on map shutdown
Fixed time-ago strings showing "-1 seconds ago"
Fixed momentum teleport triggers
Removed redundant map label inside spectator GUI
> Goodbye, Bugfix_and_QoL

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_player.h
If it's attempted, switch to the weapon that's currently at that slot and leave the new weapon on the ground. Not sure if this is the exact behavior we want.
Closes #325
> Don't allow multiple weapons to be equipped at same slot

- mp/src/game/client/momentum/mom_system_discord.cpp
- mp/src/game/client/momentum/ui/lobby/LobbyMembersPanel.cpp
- mp/src/game/server/momentum/mom_lobby_system.cpp
Main culprit was the FindItemIDForLobbyMember method not properly using the itemID versus row syntax valve has in VGUI.
Fixed some crashes with lobbies due to lack of null checks and not checking the itemID when removing users from the panel.
Closes #297
> Fix lobby member panel duplicating names

- mp/src/game/client/c_baseplayer.cpp
- mp/src/game/client/momentum/c_mom_online_ghost.cpp
- mp/src/game/client/momentum/c_mom_online_ghost.h
- mp/src/game/server/momentum/mom_online_ghost.cpp
- mp/src/game/server/momentum/mom_online_ghost.h
Instead of boring normal dimlights, full blown flashlights are supported.
Control this with `mom_online_ghost_flashlights_enable [0/1]`.
> Add Flashlights to Online Ghosts

- mp/src/game/server/momentum/mom_triggers.cpp
Hammer/FGD implied it took an angle when it actually took a direction. Changed behaviour to match trigger_push and actually accept angles.
Closes #327
> Fix func_shootboost angle mismatch

- mp/src/game/server/bmodels.cpp
Fix "SetSpeed" not properly reading float input (closes #344 )
Allow 0 speed on spawn (closes #345 )
Also updated the depot's base.fgd file to accommodate these changes, will be updated for 0.8.2
> func_conveyor fixes

- mp/src/game/client/client_momentum.vpc
- mp/src/game/client/momentum/mom_map_cache.cpp
- mp/src/game/client/momentum/mom_system_discord.cpp
- mp/src/game/client/momentum/ui/leaderboards/LeaderboardsTimes.cpp
- mp/src/game/server/momentum/mom_lobby_system.cpp
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_player.h
- mp/src/game/server/momentum/mom_system_saveloc.cpp
- mp/src/game/server/momentum/mom_timer.cpp
- mp/src/game/server/momentum/mom_timer.h
- mp/src/game/server/momentum/server_events.cpp
- mp/src/game/server/server_momentum.vpc
- mp/src/game/shared/momentum/mom_gamemovement.cpp
- mp/src/game/shared/momentum/mom_gamerules.cpp
- mp/src/game/shared/momentum/mom_system_gamemode.cpp
- mp/src/game/shared/momentum/mom_system_gamemode.h
- mp/src/game/shared/momentum/weapon/weapon_mom_rocketlauncher.cpp
A simple refactor to clarify structure and make game modes a little more flexible.
Instead of being embedded all over the place, game modes have now moved to their own interface. Game modes themselves are classes now, and events (On Map Start, OnPlayerSpawn, etc) are applied to them, so they have full control over what they actually do. Everything's nice and organized in mom_system_gamemode, and it is shared and synchronized across server and client (client actually sets it first, server updates next/same? tick). [If we had engine it'd be there]
The expansion part of this is already starting to be explored; RJ now gives the player the rocket and shotgun to start off with. Things like bhop could give knife, trikz grenades, etc. It's up to us to see what players want by default.
Closes #352 …
> Game Mode Interface

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_player.h
- mp/src/game/shared/momentum/mom_gamemovement.cpp
Crouching and ground speed cap changes from #347.  
It still seems like rockets give too much speed compared to TF2. I've been debugging this for a while now and either I'm missing something dumb, or the way it's handled in TF2 has changed since 2007.
> Rocket jumping gamemode movement changes

- mp/src/game/client/in_main.cpp
- mp/src/game/client/momentum/mom_in_main.cpp
- mp/src/game/client/momentum/ui/HUD/hud_keypress.cpp
- mp/src/game/server/momentum/ghost_client.cpp
- mp/src/game/server/momentum/ghost_client.h
- mp/src/game/server/momentum/mom_lobby_system.cpp
- mp/src/game/server/momentum/mom_lobby_system.h
- mp/src/game/server/momentum/mom_online_ghost.cpp
- mp/src/game/server/momentum/mom_online_ghost.h
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_player.h
- mp/src/game/server/momentum/mom_system_saveloc.cpp
- mp/src/game/server/momentum/mom_system_saveloc.h
- mp/src/game/shared/in_buttons.h
- mp/src/game/shared/momentum/fx_mom_shared.cpp
- mp/src/game/shared/momentum/mom_gamemovement.cpp
- mp/src/game/shared/momentum/mom_ghostdefs.h
- mp/src/game/shared/momentum/weapon/weapon_knife.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_grenade.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_paintgun.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_paintgun.h
Allows players to paint, without needing to pull out their hefty paintgun, by using `+paint`.
Also did some minor cleanup on some of the code:
* Privatized some needlessly public functions in `CMomentumPlayer`
* Changed packet structs in ghostdefs to classes & removed the `_t` suffix (it's weird to have structs with inheritance/virtuals)
* Changed the disgusting DIY aliasing on the decal packet into a union for clearer code
Closes #281
> Add +paint command

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/shared/momentum/mom_gamerules.cpp
Fixed rockets giving too much speed and fixed crouched collision box being the incorrect height, thanks to ILDPRUT. (#347 )
There's probably a better way to do the RadiusDamage stuff if it is ever used for other weapons, all the changes I've made to the default implementation have been with just rocket jumping in mind.
> Rocket self-damage fixes

- mp/src/game/server/momentum/mom_player.cpp
Start zone changes from #347:
- Start timer only on zone exit
- Do not limit speed inside the zone
> Add rocketjump gamemode start zone behavior

- mp/src/game/server/basecombatcharacter.cpp
- mp/src/game/server/basecombatcharacter.h
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/shared/momentum/weapon/weapon_cs_guns.cpp
Closes #353 
Testing the new PBR weapons was annoying when you couldn't pick up all of them at once. 
This fixes two things:
1. A regression introduced in https://github.com/momentum-mod/game/commit/87d2429d3df7b745e6d8ea9a76dcf7dfff894f65
2. The weapon switching bug (giving yourself a cs gun and couldn't switch to it) was mainly due to the CS weapon overrides not having the correct class name.
> Fixed weapon equipping / switching

- mp/src/game/client/c_baseviewmodel.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_rocketlauncher.cpp
#347 
`cl_righthand` controls if the rocket comes out of the left or right of the screen. It was made to be able to change cl_righthand only from the menu now, as per TF2's setting.
Introducing `mom_rj_center_fire`, a toggle var that controls if the rockets will come out of the center of the screen. While the rocket launcher does not currently display centered (visual bug to be fixed later), rockets will fire out of the dead center of the screen.
> Added mom_rj_center_fire and make rocket launcher respect firing mode

- mp/src/game/shared/momentum/mom_gamemovement.cpp
Implement TF2 jumping properly. sv_considered_on_ground and sv_jump_z_offset are currently defined in this file, so it is not possible to set them to 0 for rocket jumping in CGameMode_RJ::SetGameModeVars().
> TF2-style jump landing

- mp/src/game/client/c_baseentity.cpp
- mp/src/game/client/hud_pdump.cpp
- mp/src/game/client/particlemgr.h
- mp/src/game/client/physics_main_client.cpp
- mp/src/game/server/physics_main.cpp
- mp/src/public/tier0/memalloc.h
New versions of Visual Studio 2019 have removed this file altogether (integrated into the compiler?) and POSIX just uses `<typeinfo>` anyways.
Closes #390
> Remove references to typeinfo.h

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_player.h
- mp/src/game/server/momentum/mom_timer.cpp
#347 
Makes the player a listener for rockets and destroys rockets on:
* Using mom_restart
* Using mom_reset
* Exiting practice mode in a run
* Entering the start zone
> Fix Rocket Abusing Scenarios

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_player.h
- mp/src/game/server/momentum/mom_replay_entity.cpp
- mp/src/game/shared/momentum/run/mom_run_entity.cpp
Exiting the end zone with the mapfinished panel still open will automatically close, leaving no opportunity for the user to look at it. This fixes that behaviour so that the mapfinished panel remains open until the player closes it or enters start zone by restarting.
Closes #185
> Fix behaviour when exiting end zone with mapfinished panel open

- mp/src/game/client/cdll_bounded_cvars.cpp
- mp/src/game/server/gameinterface.cpp
- mp/src/game/server/momentum/mom_player.cpp
Preferred in RJ and seemingly has no effect on anything else
> Default to using 0 cl_interp and cl_interp_ratio

- mp/src/game/shared/baseplayer_shared.cpp
Before it used to shoot rockets relative to a previous position of the player, which ruined rocket jumping at high speeds.
> Set the shoot position relative to the current position of the player

- mp/src/game/client/cdll_bounded_cvars.cpp
- mp/src/game/server/momentum/mom_blockfix.cpp
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/shared/gamemovement.h
- mp/src/game/shared/momentum/mom_gamemovement.cpp
- mp/src/game/shared/momentum/mom_gamemovement.h
- mp/src/game/shared/momentum/mom_rocket.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_shotgun.cpp
Fixed:
Scorch decal only placing on floors
0.1 interp is now the default again after it was revealed to not actually do anything other than lag (closes #411 )
Doors being locked on RJ maps (closes #420 )
Ladder movement disabled for RJ (closes #421 )
Fixed shotgun not firing underwater for RJ (closes #415 )
> Fixed Various RJ Bugs

- mp/game/momentum/scripts/weapon_momentum_shotgun.txt
Some buttons were not reachable with the shotgun, so the range is now 8192, hitting a wall up to 8191 HU away.
Visual difference in range:
Should Close #416 👀
> Increase Momentum Shotgun range: 3000 -> 8192

- mp/src/game/shared/momentum/mom_gamemovement.cpp
The way the sliding mechanic works for slide triggers is that it blocks the player's ground entity from being set. This makes the game think that the player isn't standing on anything and moves the player in a way that feels like sliding. 
It also blocks mechanics like walking/jumping, so to allow jumping we check if the player intends to jump and if the AllowingJump property is set, and if so we lift the set ground entity block temporarily.
Closes #430
> Fix AllowingJump property of slide triggers

- .circleci/config.yml
- mp/src/game/server/momentum/mom_online_ghost.cpp
- mp/src/game/server/momentum/mom_online_ghost.h
- mp/src/game/shared/momentum/mom_gamerules.cpp
- mp/src/game/shared/momentum/mom_ghostdefs.h
- mp/src/game/shared/momentum/weapon/weapon_mom_rocketlauncher.cpp
Firing rockets when in lobbies will now show up in game for others. They currently do not boost other players in the lobby, nor should they do damage to anything on their instance.
> Network Rockets through Online Lobbies

- mp/src/game/shared/momentum/mom_gamemovement.cpp
Because you never have any downward velocity at WalkMove() in the rocket jump gamemode while grounded, you will just stay in the air. This fix will bring you down to the ground if you are already grounded on it.
> Bring player to the ground if grounded

- mp/src/game/client/momentum/ui/HUD/hud_fillablebar.h
Fixes the drawing bugs when trying to draw a bar with a width too small, however makes the bar for sync < 5% all look the same.
Closes #461
> Add a minimum width for sync bar

- mp/src/game/client/momentum/clientmode_mom_normal.cpp
The buttons need to be updated before the sidemove is added in
Turns out I was testing with `mom_enable_overlapping_keys 1` before 🤦‍♂ 
Closes #469
> Actually enforce disabled buttons in non-overlapping keys logic

- mp/src/game/client/hud_chat.cpp
- mp/src/game/client/hud_chat.h
- mp/src/game/server/momentum/mom_lobby_system.cpp
Added timestamps for chat messages printed in the console.
Added timestamps for the in-game chat messages.
Added a `ConVar` to toggle timestamps.
Closes #321
> Add timestamps to chat messages

- mp/src/game/shared/gamemovement.cpp
- mp/src/game/shared/momentum/mom_system_gamemode.cpp
- mp/src/game/shared/movevars_shared.cpp
- mp/src/game/shared/movevars_shared.h
Adds convar sv_duck_collision_fix. The rocket jump gamemode will not use this fix as it is undesired and unwanted headbugs will instead be fixed manually in the map. The duck code already checks if the player would be stuck when ducking/unducking and this fix only affects the tick you duck/unduck by using the correct bbox for movement checks.
> Convar fix for headbugs

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_player.h
Closes #486 
After delaying a bit in practice mode, the player was able to fire a rocket immediately as the weapon's next primary attack had already arrived. So upon exiting practice mode we now reset the primary attack to what it should be as if they never entered practice.
As for if the player changes weapon and exits practice mode, the 0.5 sec weapon switch delay effectively blocks instantly firing which should provide ample time to mess up any tricks they are setting up with this.
> Fix weapons being able to instantly fire exiting practice mode

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_player.h
Closes #468 
Savelocs are able to be edited in the savelocs.txt file to modify their gravity. Walking into a start zone, making a saveloc, quitting the map, opening the file and editing the gravity scale, saving it, reloading the map, and loading the saveloc gave the player their gravity scale, and could be abused for a run since it was not reset inside the start zone.
> Fix Saveloc Gravity Exploit

- mp/src/game/shared/momentum/fx_mom_shared.cpp
- mp/src/game/shared/momentum/mom_player_shared.cpp
- mp/src/game/shared/momentum/util/mom_util.cpp
Closes #445 
Ghosts should not be able to damage things in the local player's game, as some things like buttons rely on the local player to damage them in order to activate them.
> Fix ghosts doing damage

- mp/src/game/server/momentum/mom_player.cpp
Fixes #497
Problem was just old code that assumed commands would only be called when in the state to use them...
> Fix mom_spectate_stop teleporting player when not spectating

- appveyor.yml
This PR aims to lower the amount of unnecessary Appveyor builds by checking if only source folder (`mp/src/`) file changes are made. While the majority of the time source file changes are what's happening, there are cases where only res or texture or map files are added and don't warrant a full build.
> Limit appveyor to only build when mp/src/ files change

- mp/src/game/client/momentum/ui/HUD/hud_mapfinished.cpp
- mp/src/game/client/momentum/ui/HUD/hud_mapfinished.h
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_replay_entity.cpp
- mp/src/game/server/momentum/mom_replay_entity.h
- mp/src/game/server/momentum/mom_replay_system.cpp
- mp/src/game/server/momentum/mom_replay_system.h
- mp/src/game/server/momentum/mom_timer.cpp
- mp/src/game/server/momentum/mom_timer.h
- mp/src/game/shared/momentum/mom_shareddefs.h
Closes #439 
Fixed the date bug by preventing user teleporting at all while the AllowUserTeleport flag is false.
Cleaned up the replay system and probably got rid of some memory leaks.
Separated the process of ending a replay into Cancel / Stop / Finish, where Cancel is throwing it away, Stop is called when the timer stops (begin the delay) and Finish is called after the delay for the replay is over.
> Fix Replay Date Bug + Some Cleanup of Replay System

- mp/src/game/shared/momentum/mom_grenade_projectile.cpp
- mp/src/game/shared/momentum/mom_player_shared.cpp
- mp/src/game/shared/momentum/mom_rocket.cpp
- mp/src/game/shared/momentum/mom_rocket.h
- mp/src/game/shared/momentum/util/mom_util.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_grenade.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_grenade.h
Closes #404 
A player could enter practice mode and fly ahead to shoot/knife/etc buttons on the wall to open door before they had approached the area in the run. While the timer still runs inside practice mode, this would still remove the need for them to react to the buttons, gaining an advantage over others. This PR prevents any damage of any type when in practice mode.
> Fix players doing damage in practice mode

- mp/src/game/client/c_baseviewmodel.cpp
- mp/src/game/server/momentum/mapzones.cpp
- mp/src/game/server/momentum/mapzones_build.cpp
- mp/src/game/server/momentum/mapzones_edit.cpp
- mp/src/game/server/momentum/mom_timer.cpp
- mp/src/game/shared/momentum/mom_shareddefs.h
- mp/src/game/shared/momentum/weapon/weapon_mom_rocketlauncher.cpp
- mp/src/public/tier1/convar.h
- mp/src/public/tier1/iconvar.h
- mp/src/tier1/convar.cpp
Closes #520 
This PR introduces a new type of ConVar called ConVar_Validated, that takes in a bool func pointer that validates the new value to be set for a convar, returning true to accept and false to reject it. We cannot merge it into the base class as it ruins the vtable of ConVars already defined in engine/matsys/etc. If we get engine license, we can merge them.
`cl_righthand` and `mom_rj_center_fire` are now validated to check for if the player is in a run, and if so, to reject the change.
> Prevent changing righthand / centerfire when in a run

- mp/src/game/shared/momentum/mom_gamerules.cpp
During one of the changes in the generic bomb branch, the check for setting the rocket self-damage radius was changed to using `pAttacker` instead of the inflictor which meant that rockets would have a higher radius during push force calculations and thus make jumps like last on jump_concept trivial.
> Hotfix for setting correct rocket self-damage radius

- mp/src/game/client/momentum/ui/lobby/LobbyMembersPanel.cpp
- mp/src/game/client/momentum/ui/lobby/SavelocRequestFrame.cpp
- mp/src/game/server/momentum/mom_lobby_system.cpp
- mp/src/game/server/momentum/mom_system_saveloc.cpp
- mp/src/game/server/momentum/mom_system_saveloc.h
- mp/src/game/shared/baseentity_shared.cpp
- mp/src/game/shared/baseentity_shared.h
- mp/src/game/shared/momentum/mom_ghostdefs.h
- mp/src/game/shared/momentum/mom_shareddefs.h
Closes #462 
This PR is the second half that #525 started. This PR validates the packets used in online lobbies to help prevent garbage data from causing unforeseen consequences. For example, the saveloc request flow was actually pretty insecure as people can be added multiple times as requesters, and stages sent out of order would be obeyed and potentially cause crashes/undefined behavior. Every packet has its core data validated to be reasonable, and clamps values to invalid/default values to be properly rejected by the code. Code will never be 100% fool proof, but this is much better than it was.
As for spam prevention, Steam handles it for the most part, but could be a valid concern. Spam can be counteracted by changing the privacy settings for lobbies, though it will get properly …
> Validate Online Packets

- mp/src/game/client/momentum/ui/SettingsPanel/AppearanceSettingsPage.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/AppearanceSettingsPage.h
- mp/src/game/client/momentum/ui/SettingsPanel/ComparisonsSettingsPage.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/ComparisonsSettingsPage.h
- mp/src/game/client/momentum/ui/controls/ModelPanel.cpp
Closes #527 
Resources weren't properly being disposed of due to the panel getting completely destroyed and recreated on resolution change, so the pinned-sibling frames used to show the preview of your model/comparisons were not properly disposed of, and tried to pin to a panel that was destroyed. This PR disposes of these frames on resolution change, and *not the destructor due to the panels actually getting cleaned up when the game is shutting down*, getting rid of the crash.
> Fix crash on resolution change with momentum settings panel open

- mp/src/game/shared/momentum/mom_ghostdefs.h
Part of #462 
This PR validates the paint decal packet radius to fall within the scale used for the convar, forgot to do it during the giant validation branch. Better late than never!
> Validate paint packet decal radius

- mp/src/game/server/player.cpp
Closes #489 
Since pretty much every map is made with multiplayer servers in mind, there's no reason for player_speedmod to default to the local player; the activator will never be a non-player entity.
> Don't default to local player in player_speedmod

- mp/src/game/client/hud.cpp
Closes #557
This seems like a regression from cf983e81. The function `LoadHudTextures` was changed and no longer appended the `.txt` to the filenames, so all attempts to load files failed since they were missing the extension.
Fixing this also results in weapon crosshairs having a dot in the middle, since this bug has been around a while I'm not sure if having this is intentional or not.
Example of weapon crosshair:
> Fix missing default crosshair

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.h
This PR fixes a case where the internal sticky charge timer still counts up when trying to charge stickies inside the start zone, thus being able to fire a fully charged sticky upon leaving the start zone.
> Disallow pre charged stickies in start zone

- mp/src/game/client/client_momentum.vpc
- mp/src/game/client/momentum/tf2proxy.cpp
This PR fixes an issue with materials from live TF2 which use custom material proxies that are not in Momentum, turning models black.
> Stop TF2 materials from going pitch black

- mp/src/game/client/hud_crosshair.cpp
Custom crosshair files were maybe fixed with #561, though odd issues with the crosshair having alpha and only showing when the run comparisons panel did sometimes occurred? This might need more testing to ensure this is no longer the case.
> Stop showing default "dots" crosshair with weapon crosshairs and fix custom crosshair files

- mp/src/game/shared/momentum/mom_stickybomb.cpp
As this setting gives an objective advantage for things like airpogos, this is being set to 0 by default and anyone who wishes to change it can do so.
> Default mom_sj_stickybomb_drawdelay to 0

- mp/src/game/client/momentum/ui/HUD/hud_stickybombcharge.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.h
This PR adds a ConVar `mom_hud_sj_chargemeter_units` to allow players to see the speed at which a stickybomb will be fired when charged.
Setting it to 1 will show the speed in Hammer units:
Setting it to 2 will show the speed in percent:
> Add ConVar mom_hud_sj_chargemeter_units to show stickybomb speed when charged

- mp/src/game/client/momentum/c_mom_player.h
- mp/src/game/server/momentum/mom_player.h
- mp/src/game/shared/momentum/mom_gamemovement.cpp
- mp/src/game/shared/momentum/mom_player_shared.cpp
- mp/src/game/shared/momentum/mom_system_gamemode.cpp
- mp/src/game/shared/movevars_shared.cpp
- mp/src/game/shared/movevars_shared.h
The fix lets players bunnyhop after edgebugging, but also aims to make edgebugs more consistent. For example if the player is in the air and about to get grounded because they are within sv_considered_on_ground above the ground, then it will check if the player would have edgebugged or missed the edge entirely next tick. If so it will not ground the player (unless they are trying to bunnyhop), allowing for an edgebug (or miss). Another way it tries to make edgebugs more consistent is to always check if they player would have edgebugged if they had gotten a "max distance" edgebug, and if so, allow them to edgebug. Because more consistent edgebugs also means they are more common, this fix will be off by default so people can try it out in the next version. What "max distance" edgebugs are …
> Introduce sv_edge_fix (off by default)

- mp/game/momentum/particles/particles_manifest.txt
- mp/game/momentum/resource/ui/HudStickyCharge.res
- mp/game/momentum/resource/ui/HudStickybombs.res
- mp/game/momentum/scripts/HudLayout.res
- mp/src/game/client/momentum/ui/HUD/hud_stickybombcharge.cpp
- mp/src/game/client/momentum/ui/HUD/hud_stickybombs.cpp
- mp/src/game/shared/momentum/mom_stickybomb.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.h
General SJ touchup and fixes:
- Added water particles to particle manifest mounting
- Added `mom_hud_sj_stickycount_autohide` which can autohide the count if the count is 0
- Made the stickybomb drawdelay default to 0
- Added `mom_hud_sj_chargemeter_units` to change the label of the charge meter to be either the units of the stickybomb (1) or a percentage (2)
> SJ Touchup / Fixes

- mp/src/game/client/c_baseplayer.h
- mp/src/game/server/player.h
- mp/src/game/shared/baseplayer_shared.cpp
- mp/src/game/shared/gamemovement.cpp
- mp/src/game/shared/gamemovement.h
- mp/src/game/shared/momentum/mom_gamemovement.cpp
- mp/src/game/shared/momentum/mom_gamemovement.h
Closes #322 
Added a fix to `mom_gamemovement.cpp` which will solve the bug where hitting a slope and losing a large amount of velocity will play the landing sound of the last surface touched.
> Fixed incorrect sound when landing on slope

- mp/src/game/server/baseentity.cpp
Closes #383 
Previously, whenever an entity's angles hit ±360000 degrees on any axis (usually func_rotating), it would refuse to update its angles any further which froze the entity while showing constant warnings. Instead, the angles are now normalized to within ±180 degrees whenever the limit is hit.
> Normalize entities' angles when they hit the angle limit

- mp/src/game/server/client.cpp
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_player.h
- mp/src/game/server/momentum/server_events.cpp
- mp/src/game/server/player.cpp
- mp/src/game/shared/momentum/mom_system_gamemode.cpp
- mp/src/game/shared/momentum/mom_system_gamemode.h
- mp/src/game/shared/momentum/weapon/weapon_def.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_rocketlauncher.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_rocketlauncher.h
- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.h
- mp/src/game/shared/momentum/weapon/weapon_shareddefs.h
This PR removes the "give" command as it can be abused to spawn any entity in the game. But fear not, this PR adds a `give_weapon` command that autocompletes based on the weapons you can spawn.
Gamemodes now define what weapons they allow, and the `UNKNOWN` gametype (maps with no recognized prefix) now allow every weapon type to be had. A note about this: the rocket and sticky launchers overlap by default so one will be on the ground. You can change the weapon script temporarily to put one in a different slot, or just drop the weapon to pick up the other.
I also went and fixed impulse 101 to properly give every momentum weapon there is so you don't need any aliases or anything to give them all. It does still require `sv_cheats 1`, though!
> Take away "give" and "givecurrentammo", but give "give_weapon"

- mp/src/game/client/clientmode_shared.cpp
Closes #326 
This PR fixes modal windows not properly being "modal" and allowing inputs to the game when open. An example can be found in the linked issue, but also when players fire when left clicking outside the color picker frame for the paintgun.
> Fix modal windows not preventing input to the game

- mp/src/game/server/momentum/tickset.cpp
- mp/src/game/server/momentum/tickset.h
- mp/src/public/scratchpad3d.h
Closes #482 
Added a ConVar `sv_tickrate` which is synchronized with `sv_interval_per_tick`, equivalent to `1.0 / sv_interval_per_tick`.
Added more defined tickrates as done by bonjorno7 in 8b08aef . As far as I can see, the defined tickrates do nothing more than round within epsilon to these values, and provide an unused interface for aquiring the tickrate as a string. The hard-coded definitions possibly could be removed. If not, tickrates which do not fall into this category perhaps should have a string other than `"CUSTOM"` assigned to them.
I did not implement the suggested feature of 66 being interpreted as 66.6.., as I am not sure of the need for the special case, the default value is already at 66.0, and the repeating value can be assigned to the convar explicitly. I can certainly …
> Added sv_tickrate

- mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp
- mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.h
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_player.h
Closes #286 
When right clicking with the leaderboard open, it will now stay open when tab is released. Pressing and releasing tab again will close the leaderboard.
A flag was added to the leaderboard class to track this state, and in order to make sure the hud elements do not reappear when tab is released, the logic updating `HIDEHUD_LEADERBOARD` was moved to the client so that it could access the viewport and the visibility of the leaderboard.
> Add Leaderboard Toggle On Mouse Detach

- mp/src/game/client/momentum/fx_mom_impacts.cpp
- mp/src/game/shared/ammodef.cpp
- mp/src/game/shared/momentum/mom_player_shared.cpp
Closes #630
This fixes paint being able to do damage to open doors while having other guns (rocket/sticky launchers) out with `+paint`. Also introduced a `mom_paintgun_limit_to_world` cvar that lets players toggle if paint should apply to just the world or everything possible.
> Fix paint doing damage

- mp/src/game/client/momentum/ui/SettingsPanel/AppearanceSettingsPage.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/AppearanceSettingsPage.h
- mp/src/game/client/momentum/ui/SettingsPanel/ComparisonsSettingsPage.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/ComparisonsSettingsPage.h
Closes #589
When switching between tabs that have preview frames in the Momentum settings, the frame will still be considered visible if it is in the process of fading out. This can cause the frame to not appear when quickly switching back and forth between tabs. My solution aimed to preserve the fading effect, but it could also be solved by disabling the fading effect on the preview frames.
> Prevent preview frame from disappearing

- mp/src/game/client/momentum/clientmode_mom_normal.cpp
Closes #642 . This issue should be apart of 0.8.5.
Fixed edge case where the lobby members panel did not have mouse input when it should:
In spectate, the key bound to `+duck` now properly enables mouse on lobby members panel if it is open. Did this exactly how it is done for the map finished panel.
> fixed edge case causing lobby panel to not have mouse input

- mp/src/game/server/momentum/mom_player.cpp
Closes #652 , which should be apart of the 0.8.5 project.
Charge meter state was only being reset in the start zone enter/exit code if the sticky launcher was the active weapon. Changed this to reset the state regardless of what weapon is currently active.
> Reset chargemeter state regardless of whether stickylauncher is active

- mp/src/game/client/momentum/clientmode_mom_normal.cpp
Closes #648 
Prevented spectator mode & player changes while map finished or lobby members panel is open. This prevents the spec command bound to `mouse2` (either `+attack`, `+attack2`, or `+jump`) from executing when enabling mouse input via right click on these panels.
> Prevented spectator mode & player changes while map finished or lobby members panel is open

- mp/src/game/client/momentum/ui/HUD/hud_mapfinished.cpp
Closes #300 . This is a branch off of PR #633
Added a check in the API calls to see if the panel is visible before writing to labels. This solves the issue of the map finished panel not being reset properly when using `mom_reset` / `mom_restart` (#300).
The fix is done as described by Gocnak.
> Fixed map finish panel labels not being reset properly

- mp/game/momentum/scripts/game_sounds_momentum_weapons.txt
- mp/game/momentum/scripts/weapon_momentum_stickylauncher.txt
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.h
Closes #655 
Holding down `+attack` when charge is disabled will no longer fire a sticky before it is released. That is, apart from their velocity, stickybombs are acting as if they are charged when charging is disabled.
Added a check to see if charging is enabled in the spot that fires a sticky when it's fully charged.
> Stopped stickybomb from firing before releasing mouse1 when charge is disabled

- mp/src/game/client/momentum/ui/HUD/hud_comparisons.cpp
- mp/src/game/shared/momentum/util/mom_util.cpp
- mp/src/game/shared/momentum/util/mom_util.h
Closes #647
MomUtil::GetRunComparison and subsequently MomUtil::GetBestTime now compare against a given track number when looking up runs. Runs that are not on the same track as the current player are ignored.
> Filter run comparison by track

- mp/src/game/client/hl2/hud_credits.cpp
- mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp
- mp/src/game/client/momentum/ui/lobby/LobbyMembersPanel.cpp
Closes #559
During the credits sequence, hide the leaderboard and lobby panels if they're visible.
> Hide scoreboard and lobby panels during credits

- mp/src/public/tier1/convar.h
- mp/src/public/vgui_controls/CvarComboBox.h
- mp/src/vgui2/vgui_controls/CvarComboBox.cpp
Related to #592 
In converting cvar-tied comboboxes to cvarcombobox, I found that it did not have the needed functionality to use it on cvars with minimum values other than 0. To do this I 
1. Added `GetMin` and `GetMax` functions to `ConVarRef`.
2. Used `GetMin` to change how the combobox indexes.
3. Used `GetMax` to solve an issue where the combobox was not setting a value in some cases.
- The `Reset()` call in the constructor was removed as it didn't do anything since the items have not been added to the combobox yet.
- Added an `AddItem` override to call `Reset()` when all the items have been added to the combobox.
After this was done, the comboboxes in the momentum settings pages were converted to use this. 
The GameUI comboboxes were not changed as the current implementation …
> Extra Functionality for CvarComboBox

- mp/src/game/client/momentum/mom_api_requests.cpp
Closes #664
Self-explanatory, adds the "credits" parameter in the GetMaps API request so the credits are always included in the cache when a map is fetched.
> Added credits to maps POST request params

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/player.cpp
Closes #659 
This PR moves weapon spawn locations from giving to the center of the player's bounding box for a better chance that it will not spawn in the floor, as the issue describes. Furthermore, the check causing the gun to not be picked up through the floor was removed, as this is not a competitive game so picking up guns through walls *should* be fine (maps that use weapons do a pretty decent job of not putting them near really thin walls).
And when it comes to grabbing weapons on the map (not given to the player), the extra weapons are removed upon bumping them if the player already has the weapon, preventing annoying constant weapon switching.
> Fix weapon grabbing bugs

- mp/game/momentum/resource/ui/SettingsPanel_ComparisonsSettings.res
- mp/game/momentum/resource/ui/SettingsPanel_HudSettings.res
- mp/src/game/client/momentum/ui/SettingsPanel/ComparisonsSettingsPage.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/ComparisonsSettingsPage.h
- mp/src/game/client/momentum/ui/SettingsPanel/HudSettingsPage.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/HudSettingsPage.h
Closes #592 . This is a branch off of PR #662 
Converted the momentum settings pages to use cvarcombobox. 
The GameUI comboboxes were not changed as the current implementation `CvarComboBox` does not support
1. Cvars that have non-linear values, such as `mat_forceaniso`.
2. Comboboxes that set multiple cvars.
- eg. Filtering mode combobox sets `mat_trilinear` or `mat_forceaniso` depending on the active item.
`CvarComboBox` will need more functionality to convert the GameUI pages. Perhaps this can be tackled in #662 or another PR.
> Converted momentum settings pages' comboboxes to CvarComboBox

- mp/src/vgui2/vgui_controls/CvarToggleCheckButton.cpp
This makes the checkbutton not require an explicit `OnApplyChanges()` call to update the cvar. This is a step in the direction of removing the Apply button from the momentum settings panel.
Works when setting the corresponding cvar from console and with the settings panel's `OnCheckboxChecked()` overrides.
> Changed CvarToggleCheckButton to instantly apply when checked/unchecked

- mp/src/game/shared/momentum/weapon/weapon_mom_rocketlauncher.h
Plopy suggested this change in discord, and @Hat-Kid explained the fix: override the `DualFire()` function and have it return true. Did this exactly how it is done in the sticky launcher code.
> Allow rocket launcher to fire while attack2 is held

- mp/src/game/server/client.cpp
- mp/src/game/shared/momentum/mom_gamerules.cpp
- mp/src/game/shared/momentum/mom_gamerules.h
There is a hardcoded whitelist for commands issued by `point_servercommand` entities when `sv_allow_point_command` is set to "whitelist", and the same whitelist and execution logic is also applied to `point_clientcommand` entities. This PR adds a separate whitelist for client commands.
The new whitelist allows these client commands:
- `r_screenoverlay` - Shows a texture on the client's screen. Sometimes used by maps to convey information.
- `play`/`playgamesound` - Plays a sound directly to the client. Maps sometimes use this as an alternative to playing a sound from the world, especially when other clients shouldn't hear it.
I used a script to double check 1400+ CSGO surf and bhop maps and found no commands other than these that would need to be whitelisted (these are in fact the only …
> Appropriate whitelist for point_clientcommand

- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.h
Closes no issue - experimental.
A short buffer after detonating two stickies before detonating another is allowed. Number of ticks for buffer can be changed with cvar mom_sj_det_buffer_ticks for testing purposes, default is 5 ticks (0.075s).
> Test for a short buffer after detonating two stickies

- mp/src/game/client/momentum/tf2proxy.cpp
This stops certain TF2 models from showing the burn texture.
Closes #678
> Hardcode BurnLevel proxy to always be 0

- mp/src/game/client/momentum/ui/SettingsPanel/ComparisonsSettingsPage.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/ComparisonsSettingsPage.h
- mp/src/game/client/momentum/ui/ZoneMenu/ZoneMenu.cpp
- mp/src/public/vgui_controls/CvarTextEntry.h
- mp/src/vgui2/vgui_controls/CvarTextEntry.cpp
- Changed `CvarTextEntry` to immediately set cvar values when text is changed.
- Done via an `ApplySettings()` call after the `OnTextChanged()` override.
- Handled text when cvar is set to be out of bounds (both via the `TextEntry` and directly setting it console)
- Done using a `SetText` override that formats the incoming string. Avoids trailing zeros & allows decimal point entry.
- Removed unneed `OnTextChanged()` override in the ComparisonsSettingsPage.
Note that the cvar itself handles the case where it is set out of its bounds, however in doing that the cvar's text always has trailing 0's. Easily replicated by setting a cvar out of bounds then seeing that it set to the min or max with trailing zeros when there shouldn't be.
Initially I tried modifying the cvar's printout in this case …
> Extra Functionality for CvarTextEntry

- mp/src/game/client/momentum/mom_map_cache.cpp
Closes #206 
Changed the max value of `mom_map_download_queue_parallel` from 20 to 3. In testing, it was found that only 3 downloads can happen at the same time anyways. Also do not want players using so much bandwidth.
> Changed max value of `mom_map_download_queue_parallel` cvar to 3

- mp/game/momentum/resource/ui/SettingsPanel_AppearanceSettings.res
- mp/src/game/client/momentum/ui/SettingsPanel/AppearanceSettingsPage.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/AppearanceSettingsPage.h
Child of PR #676 . Related to issue #685 
Converted the bodygroup `ComboBox` to `CvarComboBox` & the trail length `TextEntry` to `CvarTextEntry`.
The color settings are handled in a popup so nothing was needed to be changed for those to be updated instantly.
> Changed appearance settings page's vgui controls to update instantly

- mp/game/momentum/resource/ui/SettingsPanel_GameplaySettings.res
- mp/game/momentum/resource/ui/SettingsPanel_OnlineSettings.res
- mp/src/game/client/momentum/ui/SettingsPanel/GameplaySettingsPage.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/GameplaySettingsPage.h
- mp/src/game/client/momentum/ui/SettingsPanel/OnlineSettingsPage.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/OnlineSettingsPage.h
This branch is a child of PR #676 . Related to #685
This is another step in the direction of removing the apply buttons from the momentum settings pages. 
No changes were made to `CvarSlider` since it already had functionality to update instantly. The instantiation of the `CvarSlider`s were modified to include the flag necessary for this. The `TextEntry`s corresponding to these sliders were changed to `CvarTextEntry`s. The now unneeded overrides were removed.
Also added a proper enabling/disabling of the ghost alpha override slider when the ghost alpha override enable checkbox is checked/unchecked.
With this change, the only page that will need to be changed is the appearance tab, which is a bit different. It's formatting is different than the other pages as well so probably worth it to …
> Convert momentum settings pages sliders to update cvars instantly

- mp/game/momentum/resource/ui/SettingsPanel_Base.res
- mp/src/game/client/momentum/ui/SettingsPanel/MomentumSettingsDialog.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/SettingsPage.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/SettingsPage.h
Closes #685 
Since all of the options in this panel are updated instantly now, these buttons are no longer needed. 
Did this by
- Setting the visibility of them to `false` in the creation of `MomentumSettingsDialog`
- Setting the `sheetinset_bottom` in `SettingsPanel_Base.res` to `0`. This removes the space where the buttons used to sit.
- Removed unneeded `OnApplyChanges()` override and it's `MESSAGE_FUNC`.
Screenshot of change:
> Removed unneeded OK/Cancel/Apply buttons from momentum settings dialog

- mp/src/game/shared/momentum/mom_gamemovement.cpp
- mp/src/game/shared/momentum/mom_system_gamemode.cpp
- mp/src/game/shared/momentum/mom_system_gamemode.h
Closes #539 when merged into `develop`
Found the factors based on what the jump height should be at the gamemode's default gravity & added `sv_gravity` into the calculation.
IE. found `x^2` where `jumpHeight = x^2 / (2 * baseGrav)`. For ahop, `jumpHeight ~ 21.333333` and `baseGrav = 600`.
I just used the squared value since the calculation involves squaring anyhow.
- **ahop** -> jump should be `21.333333..` at base gravity (`600`). This gives `25600` (not squared is `160`).
- **TF2** -> jump should be ~`52.200625` at base gravity (`800`). This gives `83521` (not squared is `289.0`).
- **Base** -> jump should be `57` at base gravity (`800`). This gives `91200` (not squared is `301.99337741083..`).
> Added gravity into jump height calculation

- mp/game/momentum/materials/models/weapons/mom_stickybomb_classic/mom_stickybomb_classic.vmt
- mp/src/game/shared/momentum/mom_stickybomb.cpp
This branch adds an `ArmTime` stickybomb proxy that changes the blue selfillum color of the stickybomb to only show when armed. By default, it uses a buffer that is remapping from [armtime - 0.15, armtime] to [0, 1] for a fade-in effect. You can see this proxy in action here:
https://cdn.discordapp.com/attachments/602643431453360148/701654101259452456/2020-04-20_00-42-13.mp4
The time for the pulse particle was also bumped forward 0.25 seconds to better match the arming of the stickybomb, as the default (0.8.4) time was visibly late compared to arm time.
> Add sticky armtime proxy

- mp/src/game/shared/momentum/mom_gamemovement.cpp
- mp/src/game/shared/momentum/mom_gamemovement.h
- mp/src/game/shared/momentum/mom_system_gamemode.h
Hello! I made [RNGFix](https://forums.alliedmods.net/showthread.php?t=310825) which aims to make psuedo-random physics behavior behave consistently. Momentum already contains fixes for some of these things, but not all (yet!), and this PR focuses on the uphill slopes issue.
An explanation of the issue for those unaware:
At the end of a tick of physics simulation, if the player is within 2 units of a shallow-enough surface and is not moving up too fast, they are immediately considered "on the ground", which sets their z-velocity to zero. When this happens, it means the player never actually collides with the ground and ends up landing (and jumping) as if on totally flat ground. Whether or not this happens *essentially* comes down to chance -- it just depends on how the ticks happen to line …
> Better uphill slope RNG fix

- mp/src/game/server/cbase.cpp
- mp/src/game/server/eventqueue.h
The events that we want to save with a saveloc are ones that affect the player, which we find by checking the player entity against active delayed events. (#263) However, at the time we want to restore those events, the player we want them to affect might be a different entity.
For example, one player might make a saveloc, and another player wishes to load it. Events that are part of that loaded saveloc may need to have the `activator` or other properties set to the player that is loading it. This can be handled by remembering if any of the `target`, `activator`, or `caller` entities are the entity the event was saved for, and then filling those in with the new entity when the saveloc is loaded. Essentially, those matching entities are instead treated as an abstracted/blank entity to be …
> Improved entity IO saving and restoring for savelocs

- mp/src/game/client/momentum/ui/HUD/hud_comparisons.cpp
- mp/src/game/client/momentum/ui/HUD/hud_keypress.cpp
- mp/src/game/client/momentum/ui/spectate/mom_replayui.cpp
- mp/src/game/client/momentum/ui/spectate/mom_spectator_gui.cpp
- mp/src/game/server/momentum/mom_ruler.cpp
- mp/src/game/server/momentum/mom_ruler.h
Closes #308 
This PR moves localization methods so it's possible to reload localization files without the need to restart the game.
> Move localization methods

- mp/src/game/client/c_basecombatweapon.cpp
- mp/src/game/client/c_baseviewmodel.cpp
- mp/src/game/client/c_vguiscreen.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/ComparisonsSettingsPage.cpp
- mp/src/game/server/momentum/mom_lobby_system.cpp
Closes #646
This branch fixes weapons casting shadows when in spectate, as well as fixes some things left over from previous merges like lobby spec messages happening while not in a lobby, and the bogus comparison panel in the momentum settings panel not having strings.
> Fix weapons casting shadows while in spectator mode

- mp/src/public/vgui_controls/CvarComboBox.h
- mp/src/vgui2/vgui_controls/CvarComboBox.cpp
The new CvarComboBox implementation failed to account for using up/down arrow keys to change the combobox selection. When using them the cvar isn't instantly updated, which makes the text displayed in the combobox not match what the actual cvar value is.
This fix overrides the `OnKeyCodeTyped` function to change the combobox's active item & apply that to the cvar via `ApplyChanges()`.
There are two other changes:
- Fixed `m_iStartValue` not being set correctly, causing extra `ApplyChanges()` calls.
- When the `OnTextChanged()` override is called, `ApplyChanges()` is now called only if there has been a modification.
> Fix for up/down arrow key presses on CvarComboBox 

- mp/game/momentum/resource/optionssubmouse.res
- mp/src/gameui/CvarNegateCheckButton.cpp
- mp/src/gameui/OptionsSubMouse.cpp
- mp/src/gameui/OptionsSubMouse.h
- mp/src/public/vgui_controls/CvarTextEntry.h
- mp/src/vgui2/vgui_controls/CvarTextEntry.cpp
Now that the momentum settings changed to apply instantly, I'm attempting to make the same changes to the GameUI code.
A couple of changes here:
- Changed `CvarTextEntry` to receive an optional number format override. This is useful as there are some cvars where it makes sense to use `%.3f`, `%.2f` etc. as with the mouse settings.
- Changed `CvarNegateCheckButton` to apply instantly as was done with `CvarToggleCheckButton`. 
- The GameUI's mouse options is the only place where this vgui element is used.
- Changed the mouse settings page's fields to apply instantly:
- Added the auto apply changes flag to the `CvarSlider`'s.
- Converted the `TextEntry`'s to `CvarTextEntry` & set the allow numeric input only flag.
- Removed a lot of unneeded overrides as a result of these changes.
- Renamed …
> Changed GameUI mouse settings to apply instantly

- mp/src/gameui/OptionsSubAudio.cpp
- mp/src/gameui/OptionsSubAudio.h
Now that the momentum settings changed to apply instantly, I'm attempting to make the same changes to the GameUI code - Issue #708 
Changed a few things:
- Changed the two `CvarSlider`'s to auto apply.
- Moved the code in `OnApplyChanges()` to `OnControlModified`.
- Changed `OnControlModfiied` to include the particular panel calling it. 
- Moved all the `ConVarRef` calls to the constructor.
- Separated out the apply/reset code for each combobox into helper functions to ease readability.
- Before there was many comments explaining what combobox is being updated.
The popup dialogs (the 3rd party reference & spoken language change) still work with these changes.
> Changed GameUI audio settings to apply instantly

- mp/src/gameui/OptionsSubKeyboard.cpp
- mp/src/gameui/OptionsSubKeyboard.h
Now that the momentum settings changed to apply instantly, I'm attempting to make the same changes to the GameUI code - Issue #708 
Functionality:
- Once the key is bound/deleted, it instantly applies rather than applying after pressing OK/Apply.
- ApplyOK button is used to write settings to the config file.
- My goal is to use the apply button to write the settings to the config & override the button's text to be "Write to config file". Could also write to file every time something is changed but that seems like it'd be costly.
Did this by
- Removing functions/fields related to resetting bindings when the "Close" button is pressed.
- Added `BindKey` and `UnbindKey` calls when a key is bound in the menu.
- Edit & clear key buttons work with this as well.
Also:
- Moved the advanced dialog …
> Changed GameUI keyboard settings to apply instantly

- mp/src/game/client/momentum/ui/ZoneMenu/ZoneMenu.cpp
- mp/src/game/client/momentum/ui/ZoneMenu/ZoneMenu.h
- mp/src/public/vgui_controls/CvarSlider.h
- mp/src/vgui2/vgui_controls/CvarSlider.cpp
Apart of #710 
- Added an integer only flag to `CvarSlider` for sliders that need to set cvar values as whole instead of floating point numbers. 
- Converted the grid size slider to use this flag and also the auto apply flag. 
- Removed unneeded code that was updating the slider/textentries.
> Converted Zone Menu to new CvarSlider/CvarTextEntry

- mp/game/momentum/resource/ui/PaintGunPanel.res
- mp/src/game/client/momentum/ui/PaintGunPanel.cpp
- mp/src/game/client/momentum/ui/PaintGunPanel.h
Apart of #710
- Decal scale slider now uses auto apply flag
- Converted decal scale text entry to `CvarTextEntry`
- Removed unneeded code used to update the slider/textentry as a result of this conversion.
> Converted Paint Gun Panel to new CvarSlider/CvarTextEntry 

- mp/game/momentum/resource/ui/ReplayUI.res
- mp/src/game/client/momentum/ui/spectate/mom_replayui.cpp
- mp/src/game/client/momentum/ui/spectate/mom_replayui.h
Apart of #710
- Converted the timescale slider to use the auto apply flag.
- Converted timescale text entry to `CvarTextEntry`.
- Removed unneeded code that was updating the slider/textentries.
> Converted ReplayUI fields to new CvarSlider/CvarTextEntry 

- mp/game/momentum/momentum.fgd
- mp/src/game/server/momentum/mom_triggers.cpp
- mp/src/game/server/momentum/mom_triggers.h
- mp/src/game/shared/momentum/mom_stickybomb.cpp
- mp/src/game/shared/momentum/mom_stickybomb.h
Closes #694 
This PR adds a flag to the func_nogrenades trigger which determines whether stickies that have landed should fizzle or not.
> Add airborne_only flag to func_nogrenades

- mp/src/game/client/clientmode_shared.cpp
Closes #737 
Early returned the `StartMessageMode` function when the viewport isn't visible (effectively when `cl_drawhud = 0`).
> Prevent softlock when chat is opened and cl_drawhud is 0

- mp/game/momentum/resource/ui/MapFinishedDialog.res
- mp/src/game/client/momentum/ui/HUD/hud_mapfinished.cpp
- mp/src/game/client/momentum/ui/HUD/hud_mapfinished.h
- mp/src/game/server/momentum/mom_replay_system.cpp
Closes #299
This PR Adds a label that shows the player a time difference between his best run and the run just finished.
1. Overall Time
1. Zone Time
> Map finish time comparison

- mp/src/gameui/OptionsDialog.cpp
- mp/src/gameui/OptionsDialog.h
- mp/src/gameui/OptionsSubKeyboard.cpp
- mp/src/gameui/OptionsSubKeyboard.h
- mp/src/public/vgui_controls/PropertyDialog.h
- mp/src/vgui2/vgui_controls/PropertyDialog.cpp
Closes #708 
- Changed the GameUIs property dialog to only have OK button which writes the player's config to file. This button does not close the dialog and has its text set to "write settings to config file".
- Removed unneeded apply button code. (`ApplyButtonEnable` action signals & `OnApplyChanges()` overrides).
- Added code to the `PropertyDialog` class that dynamically changes the position of the OK/Cancel/Apply buttons based on which are visible.
- Before, setting the cancel button to be not visible created a gap between the OK/Apply buttons. Since the cancel/apply buttons were set to not visible on the options dialog, the OK button was near the middle of the panel and not aligned.
May not be 100% useful given the options dialog stuff is gunna be thrown into the momentum settings …
> Removed Cancel/Apply buttons on GameUI options dialog

- mp/src/game/server/client.cpp
Closes #760
Simple catch that prevents users from giving themselves weapons in the main menu/credits.
> Prevent give_weapon command in credits & main menu

- mp/src/game/client/momentum/ui/controls/FileImage.cpp
- mp/src/game/client/momentum/ui/controls/FileImage.h
- mp/src/game/client/momentum/ui/controls/ImageGallery.cpp
- mp/src/game/client/momentum/ui/controls/ImageGallery.h
- mp/src/public/stb/image/stb_image_resize.h
- mp/src/vgui2/vgui_controls/ImagePanel.cpp
FileImage had a pretty subtle graphical issue of looking pretty garbage when the original image was scaled to fit the specific (typically smaller) viewport. Enter `stb_image_resize`, from the same repo of `stb_image` that allowed for FileImage in the first place. Although when implementing this I noticed significant performance hits upon resizing, so I threw it onto a simple thread. It may be worth it to throw loading the image onto the thread as well, but seems to be a little more complicated as URL images are loaded significantly differently than Files are.
I also noticed that we would always hit the disk/network for images that we have already loaded, especially ones that we load often (map selector icons, opening the map info page for the same map multiple times), so I created the …
> Use stb_image_resize to resize FileImages

- mp/src/game/client/viewpostprocess.cpp
- mp/src/game/client/viewrender.cpp
Closes #752
CS:S uses a different version of dev/downsample_non_hdr and forced `mat_tonemap_algorithm 0`. By applying both changes, HDR bloom in momentum is now identical to that of CS:S.
Before:
After:
CS:S for scale:
> Use the same tonemapping settings as CS:S

- mp/src/game/shared/baseplayer_shared.cpp
In CS:S, maps can have buttons textured with `tools/toolsnpcclip` or a material with `%compileNonSolid 1` so the players don't collide with them but can still +use. This PR adds the necessary flags for such buttons to function in momentum as well.
> Allow toolsnpcclip or %compileNonSolid buttons to be +used

- mp/src/public/vgui_controls/ComboBox.h
- mp/src/vgui2/vgui_controls/ComboBox.cpp
Comboboxes can get into a state where the value shown in their TextEntry is not the active item (when using up/down keys mainly). This is because the item isn't active but it is highlighted. 
This method gets the current item shown in the TextEntry by returning the currently highlighted item unless no item is highlighted, in which case it returns the active item.
Tested this with comboboxes in the advanced video settings. Changing say vsync to enabled through just arrow keys, then pressing OK. With `GetActiveItem()`, `mat_vsync` is still 0, but with `GetCurrentItem()`, it is 1.
> Method to get currently shown item in combobox

- mp/src/vgui2/vgui_controls/ComboBox.cpp
While in a map with settings open, pressing escape while a combobox is selected resets it back to the first item. This is because it calls `SelectMenuItem` with a negative value here. Escape should be used to toggle the main menu/settings and the game, not on comboboxes.
> Prevented escape key from clearing comboboxes

- mp/src/public/vgui_controls/CheckButton.h
- mp/src/vgui2/vgui_controls/CheckButton.cpp
Another useful VGUI function.
`SilentSetSelected` sets the `CheckButton` selection state without posting an action signal, akin to the `SilentActivateItem` function for `ComboBox`'s. 
Useful for loading settings from file (can differentiate between user clicking check and settings load). To do this currently you need to surround with `SetSilentMode` calls.
> SilentSetSelected method for CheckButtons

- .github/workflows/CI.yml
Can't use checkout/upload-artifact v2: https://github.com/Margen67/game/runs/687711323
This might be because the Docker image doesn't have node/git(?)
> Add Linux to GitHub Actions

- mp/src/game/server/momentum/mom_player.cpp
Closes #775 
Small change that early returns the `Teleport` function in `mom_player.cpp` when practice mode is enabled & jump is held.
Can easily lock this behind a cvar if people want that.
> Prevent teleport when holding jump in practice mode

- mp/src/game/client/momentum/ui/HUD/hud_mapfinished.cpp
Closes #780 
The value returned by `GetZoneTicks` is unsigned, and so sometimes wraps around to its upper bound, causing `diff` to be a very large number. Static casted these to signed ints to prevent that.
> Fixed large time comparison on map finished panel

- mp/game/momentum/momentum.fgd
Closes #781 
Removing the walking/sprinting spawnflags on `trigger_momentum_limitmovement` fixed the crash, but we still want these added of course.
I fixed this by skipping 2^20 on those spawnflags and it magically worked. I do not know why this was happening nor how this fixed it.
They appear in hammer fine:
Also they work in game:
https://cdn.discordapp.com/attachments/549657950201970688/714230454110388274/2020-05-24_14-23-11.mp4
> Fixed momentum.fgd crashing hammer

- mp/src/game/client/momentum/ui/MapSelection/BaseMapsPage.cpp
Closes #774 
In the map selector, the library and favorites tabs were able to be clicked on to sort, and defaulted to sorting by the name of the map. This should be disabled because there's already the library and favorites tabs to sort by anyways.
> Disable library/favorites header sorting inside Map Selector

- mp/src/creategameprojects.ps1
- mp/src/game/server/momentum/mapzones.cpp
- mp/src/game/server/momentum/mapzones.h
- mp/src/game/shared/momentum/mom_shareddefs.h
Closes #447
Saves and loads .zon files from zones/ rather than maps/. Problem: won't work if zones-folder doesn't exists.
> Move zone files to zones-folder

- mp/src/game/client/viewpostprocess.cpp
As mat_tonemap_algorithm is also defined in materialsystem with 1 as default, we have to resort to using Valve's "bad idea for now".
> Actually default to the original tonemapping algorithm

- mp/src/game/client/momentum/ui/HUD/hud_mapfinished.cpp
- mp/src/game/server/momentum/mom_replay_system.cpp
Closes #793 - Added the issue to the 0.8.5 release as well since it's hud related. Apologies if I shouldn't have done this.
Fixed this issue by fixing up some relevant code.
The `replay_save` event was not fired when the replay file was unable to be written to, despite it having a boolean `save` field that specifies whether it succeeded or not. This means every time `replay_save` is fired it's `save` field is `true`.
Every catching of this event checks whether `save` is `true`:
- `mom_run_poster.cpp`
- `hud_comparisons.cpp`
- `hud_mapfinished.cpp`
- `ClientTimesDisplay.cpp`
So having it fire regardless of whether saving succeeded has no repercussions.
Made the replay save button on the map finished panel disabled until the `replay_save` event is fired with a `save` field of `true`. …
> Fixed map finished panel not being closable when replay file can't be written

- mp/src/game/client/momentum/ui/HUD/hud_speedometer.cpp
- mp/src/game/client/momentum/ui/HUD/hud_speedometer.h
Stage enter speed displays when re-entering a stage we've already been in. This causes failing an rj or sj jump to display `0` or some low number as the enter speed.
This change stops stage enter speed from displaying when entering stages the player has already gone through. This change is only for linear maps, since staged ones display the speed on stage exit instead of enter, and those should display every time. 
Mainly only applies to jump gamemodes, assuming that re-entering a stage (checkpoint) on a linear surf map isn't really done.
> Prevent stage enter speed from displaying on stage re-enter on linear maps

- mp/src/game/client/clientshadowmgr.cpp
Regression from 59ff4cd (sorry)
r_flashlight_version2 assumed single pass flashlight rendering. Some of the code that got removed in 59ff4cd was an early-exit for non-single pass flashlight rendering, which changed the behaviour of that function.
In this PR I removed the function entirely since it's exclusively used for single pass flashlight rendering.
> Fix flashlight rendering

- mp/src/game/server/momentum/mom_lobby_system.cpp
As reported by @xen-000 , `pOtherMap` was able to be null here which has caused at least one crash. This fix just catches the case where it is null.
Not sure if this is being solved elsewhere. If so, can just close this.
> Fix for map change related crash

- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp
Issue reported by cowboyana: "In SJ, swapping weapon while charging will cause the charge sound effect to continue to play for its full duration, and every time you shoot the whole charge sound will restart and play again until you wait for it to fully end"
Fixed by just stopping the charge sound when holstering.
> Stopped sticky charge sound on weapon switch

- mp/src/materialsystem/stdshaders/wireframe_dx9.cpp
Missing shaders fall back to Wireframe_DX8 which we removed when overriding shaders. This adds it back as a fallback shader to make sure we don't get crashes.
> Fix missing shaders causing crash

- mp/src/vgui2/vgui_controls/Menu.cpp
Closes #850 
This seemed to happen only when a combobox had a menu open while the player hit escape to close the settings. The menu on the comboboxes eat escape key input, causing the `OnClose()` for the settings panel to not execute. Added a baseclass call there to prevent it from eating input.
Tested this with the other panels (zone menu & map selector) and they act the same with or without the change.
Also added the prevent/allow escape to show on the settings panel as I figure it should be there, though it change doesn't change anything. Without the menu input fix, it softlocks the game (cannot press escape to show menu nor move nor open console). Can drop that commit if we don't really need.
> Fix player getting stuck when closing settings panel

- mp/game/momentum/resource/ui/BaseChat.res
Closes #851 
Enables unicode support in all Chat fields. This should be unrelated to localization files.
Initial reproduction - https://streamable.com/zaqrxr
Testing fix - https://streamable.com/fdfz05
> Enable Unicode for all Chat input

- mp/src/game/client/momentum/ui/HUD/hud_mapinfo.cpp
- mp/src/game/server/momentum/mom_lobby_system.cpp
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_system_saveloc.cpp
- mp/src/game/server/momentum/mom_system_saveloc.h
- mp/src/game/server/momentum/mom_timer.cpp
- mp/src/game/shared/momentum/mom_gamemovement.cpp
- mp/src/game/shared/momentum/util/mom_util.cpp
- mp/src/game/shared/momentum/util/mom_util.h
Closes #852 
This PR fixes the crouching reset camera bug by introducing the idea of components to savelocs. This allows other systems to use the saveloc systems and manually specify what parts of the saveloc system they want to save and apply to the player. For start marks (and eventually the trick system), this is only the position and angle.
Also renamed the system internally to better match our newer code.
> Fix Duck Reset Camera Bug

- mp/src/game/shared/momentum/util/engine_patch.cpp
- mp/src/game/shared/momentum/util/engine_patch.h
When a static prop is initialized, it's given a special EHandle serial number, `STATICPROP_EHANDLE_MASK >> NUM_ENT_ENTRY_BITS` or `0x40000`. The problem is when a static prop with an index of 4096 or above gets initalized, its index overlaps with the serial number when both are ORed in `CBaseHandle::Init`, so the serial number becomes `0x40001`. The [check](https://github.com/VSES/SourceEngine2007/blob/master/se2007/engine/staticpropmgr.cpp#L1748) for whether an entity handle is a static prop only passes when the serial number is `0x40000`, so any static prop above 4096 would bypass the check. This causes a crash whenever such a prop interacts with trigger bounds, since it would bypass the check and the engine attempts to retrieve its edict which doesn't exist.
This PR adds a patch for a …
> Prevent crashes when there are more than 4096 static props

- mp/game/momentum/scripts/kb_act.lst
- mp/src/game/client/momentum/clientmode_mom_normal.cpp
- mp/src/vgui2/vgui_controls/Frame.cpp
Closes #849
Closes #833
This branch fixes some minor things noticed in the settings panel.
- Added sprint binding to keybinds
- Inverted the logic surrounding `mom_enable_overlapping_keys` (checked should mean "on" now)
- Hid frame grips for unsizable frames
> Minor Settings Panel Fixes

- mp/src/game/shared/momentum/util/mom_util.cpp
This changes the mounting order of TF2 and CSS Search Paths. Previously, the game folders were mounted first, then the respective VPKs. Now, the order is reversed. This is following advice from the comments of gameinfo.txt: 
> We search VPK files before ordinary folders, because most files will be found in VPK and we can avoid making thousands of file system calls to attempt to open files in folders where they don't exist.  (Searching a VPK is much faster than making an operating system call.)
and also allows TF2 ambient sounds to load properly on Linux (previously, on sj_amazon, the game would generate hundreds of warning due to missing files that did exist, then crash, but doesn't anymore with this, at least for me).
I have tested multiple maps from TF2, CSS and Momentum game modes and …
> Mount CSS and TF2 vpks before loose files

- mp/src/game/server/momentum/ghost_client.cpp
- mp/src/game/server/momentum/mom_lobby_system.cpp
- mp/src/game/shared/baseentity_shared.cpp
Fixed bugs from today's lobby testing:
Fixed `IsInLobby` receiving a lobby ID instead of steamIDs, and clamped velocity to `60000.0f` instead of `sv_maxvelocity`.
> Lobby bug fixes

- mp/src/game/server/player.cpp
Closes #770 
Sets the player's last weapon to the respective secondary on player spawn.
> Set last weapon to secondary on spawn for RJ/SJ

- mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp
Closes #887 
Happening because the leaderboard's mouse input could be enabled via code in [`clientmode_mom_normal.cpp`](https://github.com/momentum-mod/game/blob/d6d1262cc5157b71b508755de3f60dc7cbc9f3dd/mp/src/game/client/momentum/clientmode_mom_normal.cpp#L169), because it started as visible.
This sets the panel not visible at construction to avoid capturing mouse2 input at game startup.
Tested that it still toggles in game as well.
> Fix for leaderboard's mouse input being enabled on game startup

- mp/src/game/server/momentum/mom_player.cpp
If observing, return out of LoadAppearance, it'll get called by Spawn after finish speccing
Closes #844 
Tested with ghost replays and online in lobbies with Brae
> IsObserver check in LoadAppearance

- mp/game/momentum/resource/ui/HudStickyCharge.res
- mp/src/game/client/momentum/ui/HUD/hud_speedometer.cpp
- mp/src/game/client/momentum/ui/HUD/hud_stickybombcharge.cpp
- mp/src/public/vgui_controls/ProgressBar.h
- mp/src/vgui2/vgui_controls/ProgressBar.cpp
Closes #786 
Adds functionality for progress bars to have subdivision markings. Can be set in code or in res file. Works for horizontal filling progress bars (`PROGRESS_EAST` & `PROGRESS_WEST`) and also vertical filling ones (`PROGRESS_SOUTH` & `PROGRESS_NORTH`). Includes the number of subdivisions, their width, their color, and their visibility.
Added the appropriate fields for this in the charge meter's control resource, though it is off by default.
Had to add an extra "hidden" field to allow code to toggle the drawing without losing the user-defined visibility of it in the res file. Done as it should be hidden when charge meter is disabled.
Also changed to lower case `override`, converted to spaces instead of tabs, `(int)` casts to `static_cast<int>`, and removed duh comments and empty …
> Subdivision markings for progress bars

- mp/src/game/client/momentum/ui/gameui/BaseMenuPanel.cpp
- mp/src/game/client/momentum/ui/gameui/BaseMenuPanel.h
- mp/src/game/client/viewpostprocess.cpp
- mp/src/game/client/viewpostprocess.h
- mp/src/game/client/viewrender.cpp
We used to have a blur shader for the menu background that was removed because it had a heavy performance impact. This PR adds back menu background blur using the vignette blur effect found in the recently overridden `Engine_Post` shader from Alien Swarm. Contrary to the old blur shader, this has little to no performance impact and it looks better.
> Add back menu background blur

- mp/game/momentum/cfg/speedometer_default.vdf
- mp/game/momentum/resource/ui/Speedometer.res
- mp/src/game/client/client_momentum.vpc
- mp/src/game/client/momentum/ui/HUD/hud_speedometer.cpp
- mp/src/game/client/momentum/ui/HUD/hud_speedometer.h
- mp/src/game/client/momentum/ui/HUD/hud_speedometer_data.cpp
- mp/src/game/client/momentum/ui/HUD/hud_speedometer_label.cpp
- mp/src/game/client/momentum/ui/HUD/hud_speedometer_label.h
- mp/src/game/client/momentum/ui/controls/DoubleLabel.cpp
- mp/src/game/client/momentum/ui/controls/DoubleLabel.h
Adds a cvar for toggling the autolayout of speedometer. 
I used a callback func here calling `OnReloadControls` so that the layout is reset according to the control resource. Unsure if there is a better way to do this though. 
Holding off on the docs issue as this could be done through the VDF file. My implementation of that is a bit ugly. Can't directly call `g_pSpeedometer->OnReloadControls` from `LoadGamemodeData` in `hud_speedometer_data` as that creates an infinite loop (data is reloaded in the speedometer's override of it). Can call the baseclass' one instead but then that's called twice in the `OnReloadControls` override.
Is there a better way of doing that?
> Speedometer autolayout setting

- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp
Closes #912 , Related to #616 
Rarely, stickybombs did not fire. This still occurred when setting the buffer to be larger than the time per attack (0.6s). Seems to be occurring right at the end of the buffer. Video of issue: https://www.youtube.com/watch?v=sujo-CzoSrA
I found that there was a rare case where the player clicked & released inside of the buffer, but `m_flChargeBeginTime` was not updated. In particular, when [this `else if` branch was never executed in the buffer](https://github.com/momentum-mod/game/blob/3ae2a0bb11228af72d0a47dcc5695bb41df8802c/mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp#L189).
This fix catches the case where the buffer was _just_ missed, and fires a sticky. This bug seems to only be when M1 was not being pressed anymore; holding …
> Fix rare case where sticky does not fire

- .github/ISSUE_TEMPLATE/bug-report.md
I frequently wonder whether a bug was reported on the current released steam version or just on develop branch so I took the liberty to add that info to the template, alongside OS information.
> Add branch information to bug issue template

- mp/src/game/client/momentum/ui/HUD/hud_speedometer.cpp
First part of #918 
Removed the `bLinear != bExit` with something more explicit, allowing exit vel to be updated when exiting start zone on linear maps.
> Show start zone exit speed on linear maps

- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp
Found a little bug relating to the sticky launcher charging animation while testing @VortexParadox 's new weapon viewmodels branch ( #933 )
When the sticky launcher charge is disabled (eg. entering a start zone) while it is currently charging, the charging animation (`ACT_VM_PULLBACK`) is not reset to `ACT_VM_IDLE`.
> Properly reset sticky launcher charge animation

- mp/src/game/shared/baseviewmodel_shared.cpp
This PR adds commands to set the viewmodel offset in 3 axes:
`viewmodel_offset_x`
`viewmodel_offset_y`
`viewmodel_offset_z`
Closes #939
> Add viewmodel_offset commands

- mp/src/game/client/momentum/client_events.cpp
The `retry` command is often used by players to reconnect to servers on other games, and often they can try to do the same here which can cause issues. Not to mention the command is useless in Momentum because it doesn't actually reload the map or even reset entities. So `retry` was simply turned into an alias of `reload`.
Closes #940
> Redirect the retry command to reload

- mp/game/momentum/momentum.fgd
- mp/src/game/server/momentum/mom_triggers.cpp
- mp/src/game/server/momentum/mom_triggers.h
Closes  #865
Adds the trigger_momentum_catapult to mimic the trigger_catapult present in tf2.
This is not 1:1 as per the tf2 fgd: vphys and the random angular impulse are not currently supported, exposed options for the think interval
> Add catapult 

- mp/game/momentum/momentum.fgd
Re-add the EveryTick fgd value to trigger_momentum_setspeed that was accidentally removed in 9204dcf24492b3b131cd92b7d185b8954d60ec3e
> Re-add the EveryTick fgd value to trigger_momentum_setspeed

- mp/game/momentum/momentum.fgd
Closes N/A
Simply adds the Toggle BaseClass to the Momentum FGD to remove an error.
This should also allow the func_nogrenades brush entity to be selected.
> Add Toggle BaseClass to remove error

- mp/src/game/client/momentum/ui/gameui/BaseMenuPanel.cpp
- mp/src/game/client/momentum/ui/gameui/BaseMenuPanel.h
- mp/src/game/client/momentum/ui/gameui/mainmenu/MainMenu.cpp
- mp/src/game/client/momentum/ui/gameui/mainmenu/MainMenu.h
- mp/src/game/client/viewpostprocess.cpp
Closes #959
Opening the menu and/or console is still broken in tools mode and I imagine that will require engine to fix.
> Fix constant menu blur while in tools mode

- mp/src/game/client/momentum/ui/HUD/hud_stickybombcharge.cpp
This was missing a check of whether the `zone_enter`/`zone_exit` events were fired by the local player. I did this how the speedometer is done.
Tested with Imbellis.
> Fix chargemeter being updated by other players

- mp/game/momentum/momentum.fgd
- mp/src/game/server/momentum/mom_triggers.cpp
- mp/src/game/server/momentum/mom_triggers.h
- mp/src/game/shared/momentum/mom_stickybomb.cpp
Closes #957 
This pull request adds the aforementioned "fizzling immediately" properties for func_nogrenades in regards to the stickybomb launcher; allowing you to choose between fizzling when the player dets (the original functionality), having the sticky be fizzled once it lands (if airborne only is `false`, otherwise acts as it originally did), or having the sticky be fizzled immediately upon entering the func brush
> Added "Fizzling Immediately" properties for func_nogrenades

- mp/game/momentum/cfg/speedometer_default.vdf
- mp/src/game/client/momentum/ui/HUD/hud_speedometer_data.cpp
- mp/src/game/client/momentum/ui/HUD/hud_speedometer_data.h
- mp/src/game/client/momentum/ui/HUD/hud_speedometer_label.cpp
- mp/src/game/client/momentum/ui/HUD/hud_speedometer_label.h
When the speedometer setup or it's ordering are incorrect/missing, load from the default speedometer data set.
Also:
- Removed a `SaveToKV` method in `SpeedometerLabel` that is no longer needed. 
- Changed the name of the `LoadFromKV` method to `ApplyKV` to better fit the naming scheme in the speedometer data.
- Added missing "colorize"/"units" fields in the default speedo data set. I feel that the default file should contain all defaults.
> Load defaults from speedometer data when missing

- mp/src/public/vgui_controls/Frame.h
- mp/src/vgui2/vgui_controls/Frame.cpp
Closes #982
This PR fixes a softlock found by hex by preventing modal panels from becoming modal multiple times, which in turn made them set themselves to modal before deleting themselves... not pretty. Cleaned up the modal logic to prevent this from happening ever again in the first place.
> Fix Main Menu Softlock

- mp/src/game/client/c_baseentity.cpp
- mp/src/game/client/momentum/ui/controls/ModelPanel.cpp
- mp/src/game/client/momentum/ui/controls/ModelPanel.h
- mp/src/game/client/momentum/ui/gameui/mainmenu/MainMenu.cpp
Closes #981
This PR adds a default cubemap to use for the model panel. Since the model panel is only used in the menu and settings panel, it is hardcoded to use the default cubemap, but can be expanded in the future to update cubemaps based on the background textures (unlocked progress?), or be customized completely via res file or something.
Fixed a regression from my earlier changes and did some minor optimizations to the ModelPanel class.
Tested it by going in game, both LDR and HDR, and changing model / resolution settings. Solid as far as I know.
> Add Cubemap to Main Menu Model

- mp/src/game/shared/momentum/run/mom_run_safeguards.cpp
- mp/src/game/shared/momentum/run/mom_run_safeguards.h
The menu-related safeguards were never hit since all safeguards were early returned if they were in the main menu.
Introduces a bool field that specifies whether the safeguard should be ignored while in main menu.
> Fix menu-related safeguards always returning false

- mp/src/game/client/momentum/clientmode_mom_normal.cpp
- mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp
- mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.h
Closes #992
Whenever you open the leaderboard now, you can close it by pressing "Escape" instead of pressing "Tab" again. It also makes it so that the main menu does not open whenever you press "Escape", similar behaviour which is also seen in the chat script.
> Make escape key close leaderboard

- mp/src/game/client/c_baseanimating.cpp
Closes #996 
This PR fixes the issue of muzzle flashes showing while the viewmodel is hidden for the pistol
> Disallow muzzle flash if viewmodel is hidden

- mp/game/momentum/materials/tools/toolsblockbullets2.vmt
Closes N/A
`blockbullets2` is identical to the regular `blockbullets` but adds a compile flag in its VMT so that it is supposedly compiled as a detail brush and doesn't cut visleaves.
I've just copied it over since it's a simple VMT that might be good to have for Jump mappers in particular, since it is from TF2 mainly.
> Add blockbullets2 VMT to material/tools folder

- mp/src/game/client/momentum/ui/controls/ModelPanel.cpp
As reported by @bltech, the ModelPanel cubemap logic was incorrectly overriding the cubemap and causing things in game to have the main menu cubemap applied to them.
The correct logic to use here is to cache off the previous cubemap before setting the override, then to set it back to the cached cubemap after rendering.
> Fix ModelPanel cubemap override logic

- mp/src/game/client/momentum/ui/SettingsPanel/SettingsPanel.cpp
Closes #990 
Fixes settings panel focus
> Fix settings panel focus

- mp/src/game/client/momentum/ui/SettingsPanel/MomentumSettingsDialog.cpp
Closes #937
This PR makes it so that the Settings panel will remember the last selected tab, automatically opening to it when the player opens the settings, as well as a ConVar deciding whether or not it will engage in said behavior
Docs PR can be found [here](https://github.com/momentum-mod/docs/pull/106)
> Settings panel remembers last opened tab

- mp/src/game/client/c_baseanimating.cpp
Closes #995
Fixes shotgun playing cocking sound on 8th shot by stopping animations (apart from the muzzle flash) from playing when the viewmodel isn't drawn via `r_drawviewmodels 0`.
This is trivial though I had it assigned to myself as I wanted to see why the cocking sound isn't played when in third person (regardless of `r_drawviewmodels`). Couldn't find the reason after searching for awhile and starting to think it's more trouble than it's worth. 
From what I gather there is something stopping viewmodel animations in third person view but can't find exactly what or if that'd have any weird side effects.
> Dont process viewmodel animation when it isn't shown

- mp/src/game/client/momentum/ui/SettingsPanel/InputSettingsPanel.cpp
- mp/src/game/client/momentum/ui/controls/ModelPanel.cpp
Closes #1019 
The previous way worked because the settings panel it came from wasn't full screen, so the modal popped up correctly.
> Use g_pMessageBox to create default binds confirm prompt

- mp/src/materialsystem/stdshaders/pbr_dx9.cpp
Closes #1012 
For those looking to use a color value on models, it turns out `$color` was cursed from the start and the solution is `$color2`.
According to Sears, `$color` is used in lightmapped calculations and likely overwritten, so `$color2` was invented to allow models (on VertexLitGeneric) to be able to still have a color input.
> Use $color2 for PBR materials on models

- mp/game/momentum/momentum.fgd
- mp/src/game/server/momentum/mom_system_saveloc.cpp
- mp/src/game/server/momentum/mom_system_saveloc.h
- mp/src/game/server/momentum/mom_triggers.cpp
- mp/src/game/server/momentum/mom_triggers.h
Closes #922
Only untoggles if the teleport is a `CTriggerMomentumTeleport` as not all teleporting of the player should reset inputs.
Uses defined but unused `AfterTeleport` function.
Probably should've been a good first issue but I had already assigned to myself.
> Cvar for automatically untoggling inputs on teleporting via a Momentum teleport

- mp/src/game/server/momentum/mom_system_saveloc.cpp
Closes https://github.com/momentum-mod/game/issues/1024
I think the `trigger_multiple` being incorrect is a red herring. I had originally thought that [`m_OnTrigger.FireOutput`](https://github.com/momentum-mod/game/blob/1cf4feebeed3868227863a9e256d8338dc300ded/mp/src/game/server/triggers.cpp#L930) was what caused [`InputSpeedMod`](https://github.com/momentum-mod/game/blob/761cd228132127068a93b4d44c44aa42a3ef5551/mp/src/game/server/player.cpp#L6919) to call, but it appears it isn't. This is a trivial solution. Might not be the best, though I feel the disabled buttons need to be reset before the saveloc adds its disabled buttons.
Tested that this works when saveloc tele'ing into a speedmod (regardless of whether we're already in it, because of …
> Reset disabled buttons on saveloc tele

- mp/src/game/shared/momentum/mom_system_tricks.cpp
Closes https://github.com/momentum-mod/game/issues/1028
Adds some missing checks for whether the gamemode is tricksurf as it caused the related issue.
I searched each function in the trick system to find those used outside of the system and not checked, which turned out to just be the 2 called in `ManualTeleport`.
> Add missing checks for tricksurf gamemode

- mp/game/momentum/scripts/HudLayout.res
Closes #1002 
Moves the chat down and makes it smaller to not have the saveloc saved notification overlay the gui.
- [ x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x ] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [ x] My commits are relatively small and scoped to the best of my ability
- [x ] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x ] My branch is functionally complete; the only changes to be done will be those potentially requested in code review
> fix saveloc overlay bug

- mp/src/game/client/momentum/ui/MapSelection/MapInfoDialog.cpp
- mp/src/game/client/momentum/ui/MapSelection/MapInfoDialog.h
Closes #987 
The crash happens when opening the map info dialog then closing it before times are loaded. The panel is set to auto delete on close and the API calls execute code that references the panel's fields after the panel is closed (and deleted), causing an access violation.
This change simply stops the panel from closing until the API calls for times are completed. This is the only solution that I see other than making this a singleton, which seems unfitting.
Also:
- Fixes the times buttons being able to be pressed when their API call cannot be sent because of the `UPDATE_INTERVAL`.
- Fixes the `UPDATE_INTERVAL` from being effectively doubled. It is now 5 seconds.
> Fix crash when closing the map info panel too quickly

- mp/src/game/client/momentum/ui/HUD/hud_versioninfo.cpp
When building Develop, the last version number of the Steam version is shown which can be misleading, so I had an idea to see if it could be replaced with generic text instead whenever the game is built in Debug. The version number appears as normal when the game is built in Release.
Just a quick idea, might be useful to see if someone's on a development build.
> Replace Version Number with "Development Build" when game is built in Debug mode

- mp/src/game/client/momentum/ui/chat/ChatPanel.cpp
Closes #1041
The container was only getting mouse input when a lobby is made and the drawer's chat is clicked into. This adds `SetMouseInputEnabled(true)` calls to make the chat container and chat panel have mouse input when hud chat is opened. 
This doesn't happen with the drawers chat. I believe that's because the drawer already has mouse input. Not really sure what code makes mouse input enabled for the hud chat when the drawer's is clicked into though.
> Fix hud chat container not having mouse input

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_player.h
- mp/src/game/server/momentum/mom_system_saveloc.cpp
- mp/src/game/server/momentum/mom_system_saveloc.h
Closes #906
Saves startmarks into savedlocs.txt given that the player is in a local session. The startmarks are saved in the form:
```
"MOMSavelocSystem"
{
...
"[mapname]"
{
...
"startmarks"
{
"[track number]"
{
[saveloc data]
}
etc.
}
... 
}
...
}
```
This is implemented using a very similar system to the existing savelocs system, except that the loading must be done AFTER the player has joined, and so this is called by the actual player rather than the game system as none of the overridable functions act in this timeframe.
> Save startmarks to file

- mp/src/game/server/momentum/mom_player.cpp
Closes #1043 
Stops players from abusing gaining ground by using `mom_restart_stage` as soon as they hit the stage zone.
> Prevent teleporting to a stage while in it

- mp/game/momentum/materials/momentum/zone_material.vmt
- mp/game/momentum/materials/momentum/zone_material_overlay.vmt
- mp/src/game/client/momentum/c_mom_triggers.cpp
- mp/src/game/client/momentum/c_mom_triggers.h
- mp/src/game/server/momentum/mom_triggers.cpp
- mp/src/game/server/momentum/mom_triggers.h
- mp/src/game/shared/momentum/mom_shareddefs.h
Closes #909 
- Drawn very similarly to zone outlines, using `debugoverlay`.
- Only draws side faces as bottom/top faces are complex with `debugoverlay`.
- Only draws outline/faces if the zone if a start zone or on current track.
- Cvars for each zone type a la the outline.
Gross thing is that it draws through walls a bit, and also the duration is arbitrary. 0 duration like the outline causes flickering, so does values larger or smaller than 0.001. Doesn't seem to be framerate dependant. Larger values also work but then lags the game a lot.
> Ability to draw a zone's side faces, not just outline

- mp/game/momentum/momentum.fgd
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_triggers.cpp
- mp/src/game/server/momentum/mom_triggers.h
Closes #763 
This PR adds a new zone type, `trigger_momentum_timer_cancel`, which allows mappers to stop the timer without submitting the run.
The main reason for this would perhaps be for invalidating runs if a player takes an unintended shortcut, or maybe for some kind of "non-gameplay" area which could be found after start.
Related docs PR is opened at [#117](https://github.com/momentum-mod/docs/pull/117)
> Update trigger_momentum_timer_stop to have "Cancel" property

- mp/src/game/shared/momentum/mom_system_gamemode.cpp
Closes #1069 
Conc grenade was not being properly restricted from other gamemodes (every gamemode minus TF2-based ones).
> Blacklist conc grenade from other gamemodes

- mp/src/game/server/momentum/mom_player.cpp
This was causing the sprint sound to play when hitting the keybind for it in spectate.
> Fix sprint/walk changes being handled while spectating

- mp/src/game/client/momentum/ui/leaderboards/LeaderboardsTimes.cpp
Closes #1075 
This is weird:
When not in mapping mode, an early return is hit because `m_bUnauthorizedFriendlist` is `false` on initialization. This caused the friends times API call to never be called. In mapping mode it is initialized to `true`. 
There was no explicit initialization of this `bool`  in the constructor so I added that and it fixed the issue.
> Fix for friends times only showing in mapping mode

- mp/src/game/server/momentum/server_events.cpp
- mp/src/game/server/momentum/server_events.h
Relevant to #1084 
I've just emptied the `OnGameOverlay()` function so that the `unpause` Server Command isn't called.
> Remove "unpause" Server Command from OnGameOverlay()

- mp/game/momentum/scripts/game_sounds_momentum_weapons.txt
- mp/game/momentum/scripts/weapon_momentum_rocketlauncher.txt
- mp/game/momentum/scripts/weapon_momentum_stickylauncher.txt
- mp/src/game/server/momentum/mom_online_ghost.cpp
- mp/src/game/server/momentum/mom_triggers.cpp
- mp/src/game/shared/momentum/mom_explosive.cpp
- mp/src/game/shared/momentum/mom_explosive.h
- mp/src/game/shared/momentum/mom_rocket.cpp
- mp/src/game/shared/momentum/mom_rocket.h
- mp/src/game/shared/momentum/mom_stickybomb.cpp
- mp/src/game/shared/momentum/mom_stickybomb.h
- mp/src/game/shared/momentum/run/mom_run_entity.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.h
Closes #1048 
Adds explosive fizzle sounds to `CMomExplosive`'s. Default sound is on the quiet end and is just a placeholder for when we make a custom sound.
Adds a `Fizzle()` virtual function to `CMomExplosive` and removed the field from `Destroy`. Fizzle destroys the explosive, then plays the fizzle sprite and sound.
Fizzle sounds for specific weapons are easy to add; just override `GetFizzleSound()` with the sound script.
Also cleans up the stickybomb launcher and stickybomb code:
- Removes the `bFizzle` field from `DetonateRemoteStickybombs` in the launcher. Fizzling code is mostly in the stickybomb and this function was never called with this field as true.
- Removes `m_bFizzle` in the stickybomb code. Seems like this was used to interface with `DetonateRemoteStickybombs` and has …
> Add explosive fizzle sound

- mp/src/game/client/momentum/ui/gameui/mainmenu/drawer/lobby/LobbySearchPanel.cpp
This PR fixes a small and rare bug with lobby names being corrupted by improving the logic used to get the lobby name, passing the KeyValues directly in as opposed to returning and using a stack-temporary return value.
> Fix Menu Drawer Lobby Name Corruption Bug

- mp/src/game/server/momentum/ghost_client.cpp
- mp/src/game/server/momentum/mom_lobby_system.cpp
- mp/src/game/server/momentum/mom_online_ghost.cpp
- mp/src/game/shared/momentum/mom_ghostdefs.h
Closes #1095 
This PR hardcodes the mom_ghost_online_updaterate cvar by adding a new macro to ghostsdef.h, and removing said cvar; replacing old usages of the cvar with the macro in the process
> Hardcode online ghost update rate

- mp/src/public/vgui_controls/ScrollBarSlider.h
- mp/src/vgui2/vgui_controls/ScrollBar.cpp
- mp/src/vgui2/vgui_controls/ScrollBarSlider.cpp
Closes #1078 
Upon clicking and holding down mouse on the scrollbar track, the bar will continue to scroll as if  you were holding down the button for it
Added shift + click to instantly jump to where the user clicks
https://gfycat.com/rigiddarlingaustraliankelpie
> Improve ScrollBar track clicking

- mp/src/vgui2/vgui_controls/Frame.cpp
Closes #910 
This helps with grabbing the top of the console, for example, as the client area is rather far down compared to some other frames
Fixed an oversight where the Y wasn't initialized to any value in GetClientArea
> Improve Frame top (caption) grip sizing

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/shared/momentum/run/mom_run_safeguards.cpp
- mp/src/game/shared/momentum/run/mom_run_safeguards.h
Closes #1068 
- Resets all run safeguards when entering start zone
- Resets the `mom_restart_stage` safeguard when entering a stage/checkpoint zone
- Resets the double press safeguard when it is not safeguarded (when it returns false)
- Actions could happen with no safeguard after they have been safeguarded once as this was not being reset (IE opening chat should always be safeguarded, not failing to be when spammed)
For now, "reset" refers to the double press safeguard's `m_flLastTimePressed`.
Zone entering resets can't happen in their respective `TimerCommand_*` methods because the player can hit those without explicitly restarting. 
Stops the case where: press once, get safeguarded > restart by failing > exit zone > do command again & not get safeguarded.
> Properly reset run safeguards

- mp/game/momentum/custom/overrides/scripts/weapon_momentum_rocketlauncher_stock.txt
- mp/game/momentum/custom/overrides/scripts/weapon_momentum_rocketlauncher_tf2_original.txt
- mp/game/momentum/custom/overrides/scripts/weapon_momentum_rocketlauncher_tf2_stock.txt
- mp/game/momentum/custom/overrides/scripts/weapon_momentum_stickylauncher_tf2.txt
- mp/game/momentum/scripts/game_sounds_weapons_tf.txt
- mp/game/momentum/scripts/weapon_momentum_rocketlauncher.txt
To match the default firing position cvar value.
> Default the RJ viewmodel to the centered version

- mp/src/game/client/c_baseviewmodel.cpp
- mp/src/game/client/momentum/c_mom_player.cpp
- mp/src/game/client/momentum/c_mom_replay_entity.cpp
- mp/src/game/client/momentum/ui/HUD/hud_comparisons.cpp
- mp/src/game/client/momentum/ui/HUD/hud_keypress.cpp
- mp/src/game/client/momentum/ui/HUD/hud_speedometer.cpp
- mp/src/game/client/momentum/ui/HUD/hud_strafesync.cpp
- mp/src/game/client/momentum/ui/HUD/hud_timer.cpp
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_replay_entity.cpp
- mp/src/game/server/momentum/mom_system_saveloc.cpp
- mp/src/game/server/momentum/mom_system_saveloc.h
- mp/src/game/server/momentum/mom_timer.cpp
- mp/src/game/shared/momentum/run/mom_entity_run_data.cpp
- mp/src/game/shared/momentum/run/mom_entity_run_data.h
- mp/src/game/shared/momentum/run/mom_run_safeguards.cpp
Closes #723
This PR introduces a very nice tool for mappers and players alike: storing the current time in savelocs. This allows players to create savelocs when on a run (or continuing a timed saveloc) to time routes and see if there are potentially better routes to go through.
https://gfycat.com/verifiablesmugelver
Note that if you also hit the end trigger, it will pop open a faux end panel and let you compare against your PB's overall time. It doesn't do this live during the "run" as the stats related to this are more tied to the run replay than the player. But it can be something to expand upon this in the future.
Also note that this is only when a timer was previously running. If players want to time starting from a specific saveloc, they may edit the savedlocs.txt file to have this …
> Store Time in Savelocs

- mp/src/game/server/momentum/mom_system_saveloc.cpp
- mp/src/game/server/momentum/mom_system_saveloc.h
Closes #1104 
Mappers can now import a previous map's savelocs easily with the `mom_saveloc_import` command, which auto-completes to maps with savelocs, and appends them to the end of your current saveloc list.
> Add Saveloc Importing ConCommand

- mp/src/game/client/momentum/clientmode_mom_normal.cpp
- mp/src/game/client/momentum/ui/HUD/hud_mapfinished.cpp
Closes #1091 
This PR fixes specific commands going through the mapfinished panel even when `mom_mapfinished_movement_enable` is false.
> Fix certain commands going through mapfinished panel

- mp/src/game/client/momentum/ui/HUD/hud_timer.cpp
Closes #1113 
This PR fixes a bug found when hiding the hud timer panel. If the timer is hidden, it doesn't have the OnThink method where it gets all of its data set be called. Thus, you could "store" information about a previous run in the panel by hiding it, doing a run with comparisons, then going to a new map with no comparisons.
> Fix HUD timer not properly updating when hidden

- mp/src/game/client/momentum/ui/gameui/BaseMenuPanel.cpp
- mp/src/game/client/momentum/ui/gameui/BaseMenuPanel.h
Closes #885
VGUI Input provides a hook to distribute KeyEvents that weren't handled at all to interested parties. Using this, we can check these events for toggleconsole and showconsole and in that case toggle the console manually. I chose BaseMenuPanel arbitrarily for this, it could be any other panel really.
This works with any keybind (sadly not mousebinds) and on any panel (main menu drawer!), even engine panels (e.g. mat_texture_list) apart from full-screen stuff like the settings and the leaderboards if you right-click.
This seems like the cleanest way I could find.
> Allow opening console from everywhere

- mp/src/game/server/momentum/mapzones.cpp
- mp/src/game/server/momentum/mom_timer.cpp
Closes #1116 
Changes `mom_restart_stage` to not restart the whole map if the map is only one stage.
> Changes `mom_restart_stage` to not restart the whole map if the map is only one stage. (#1116)

- mp/src/devtools/makefile_base_posix.mak
- mp/src/nbproject_default/configurations.xml
Docs PR momentum-mod/docs#149
New compiler needs amd64 chroot to function properly
> Linux now needs amd64 chroot

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_player.h
- mp/src/game/server/momentum/mom_system_saveloc.cpp
- mp/src/game/server/momentum/mom_system_saveloc.h
- mp/src/game/server/momentum/mom_timer.cpp
Closes #221 
Adds start marks for stages that are reset on new runs. Also moves start mark code to the saveloc system.
- Since it stops the timer, I had to circumvent `ManualTeleport` in a way I'm not happy with but don't see a better option.
- Made it so players can `mom_restart_stage` to them while in the zone since that can't be abused (need to be there already before teleporting to it).
- Minor refactor of the start mark code when moving it over to the saveloc system. Might've identified a memory leak [here](https://github.com/momentum-mod/game/blob/ac0416a947feb5b14dd00629abcfd4e08223b8cd/mp/src/game/server/momentum/mom_player.cpp#L255)? Anyway should now properly be deleted.
- Don't like how similar the start mark vs stage mark code is. On hindsight should've probably just …
> Temporary, per-run stage start marks

- mp/src/utils/zonmaker/zonmaker.cpp
I missed properties subkey in start zone
> Fix missing subkey for start zone properties

- mp/game/momentum/resource/ui/GhostEntityPanel.res
- mp/src/game/client/momentum/ui/GhostEntityPanel.cpp
- mp/src/game/client/momentum/ui/GhostEntityPanel.h
Closes #847 
Got the opportunity to quickly solve this.
- Centers entpanels
- Allows their height to properly scale with resolution
- Allows the avatar image size to scale with resolution
640x480:
1280x720:
1920x1080:
> Ghost entpanels scale with resolution & are centered

- .circleci/config.yml
More often than not, CirceCI build dies while compiling. Primary suspect is running out of memory.
> Fixing CirceCI check

- mp/src/game/shared/momentum/weapon/weapon_mom_concgrenade.cpp
- mp/src/game/shared/momentum/weapon/weapon_mom_concgrenade.h
require a repress of +attack after a handheld
Requested in #802
> Implement conc repress

- mp/src/vgui2/vgui_controls/ComboBox.cpp
- mp/src/vgui2/vgui_controls/Menu.cpp
> Fix using arrow keys resetting selection to first item after selecting from dropdown

- mp/src/game/shared/gamemovement.cpp
Closes a card for 0.8.7
`m_flUpMove` is what comes from `+moveup` and `+movedown` so just cut that out of the speed.
> Prevent +moveup & +movedown from effecting ground movement

- mp/src/game/client/momentum/c_mom_triggers.cpp
- mp/src/game/client/momentum/c_mom_triggers.h
- mp/src/game/server/momentum/mom_triggers.cpp
- mp/src/game/server/momentum/mom_triggers.h
- mp/src/game/server/triggers.cpp
Closes #341 
Adds the ability to draw teleport destinations, like showtriggers. A square is drawn at the base of them, using the zone drawing material for now.
cvars:
- `mom_teledests_draw` - toggles showing them. Not archived, defaulted to off
- `mom_teledests_color` - default white
- `mom_teledests_dimensions` - controls the dimension of the square
There is one issue however: tele dests stop drawing when the center of them is not in view. I'm guessing because this a technically just a point? 
https://www.youtube.com/watch?v=j8M1SCq-_L4
> Ability to draw info_teleport_destinations in game

- mp/src/game/server/momentum/mom_lobby_system.cpp
- mp/src/game/server/momentum/mom_lobby_system.h
All packet data from blocked players is now ignored, and ghosts are immediately created if the player just got unblocked.
Partially addresses #237
> Immediately remove ghosts of blocked players

- mp/src/public/tier1/ilocalize.h
- mp/src/tier1/ilocalize.cpp
Simplified most of CLocalizedStringArg and CConstructLocalizedString operation, now uses variadic templates, and is future-proof for all standard types
> Refactor ILocalize

- mp/src/game/client/momentum/ui/controls/UserComponent.cpp
- mp/src/game/client/momentum/ui/controls/UserComponent.h
- mp/src/game/client/momentum/ui/gameui/mainmenu/drawer/lobby/DrawerPanel_Lobby.cpp
- mp/src/game/client/momentum/ui/gameui/mainmenu/drawer/lobby/DrawerPanel_Lobby.h
- mp/src/game/client/momentum/ui/gameui/mainmenu/drawer/lobby/LobbyInfoPanel.h
- mp/src/game/client/momentum/ui/gameui/mainmenu/drawer/lobby/LobbyMembersPanel.cpp
- mp/src/game/client/momentum/ui/gameui/mainmenu/drawer/lobby/LobbyMembersPanel.h
Closes #1162 
Unfortunately there's no steam callback for changing names (at least from what I read of the steamworks API), so I took the approach of just updating it more often.
- Main menu user component updates when drawer is closed. Not on open as you can't see it with the drawer open anyhow.
- Profile page's user component updates when the tab is clicked on. For some reason `OnPageShow` isn't being called when opening the drawer though. Intentional?
- Lobby name & avatar now update with any lobby change.
- Fixed steam name being always being overwritten by user data in user component (`SetUser` sets the steam name then calls `FillControlsWithUserData` that overwrites it with the one in user data). Result though is us not using the locally stored username.
> Update player's name on user components and lobby members panel

- mp/src/devtools/makefile_base_posix.mak
- mp/src/nbproject_default/configurations.xml
When I first built the GCC-9 steam runtime environment (mid June), I wasn't able to get it to build game with GCC distributed in runtime (gcc-9-monolithic). Now that I managed to build and run game with that version, I'm switching to it. Current runtime also has this newer GCC version, so CI should pass for now. I'll update the docker after this gets merged.
> Use official distributed version of gcc-9 from steam runtime

- mp/src/game/server/momentum/mom_triggers.cpp
A minor oversight in the trigger_teleport code meant that the destination no longer updates when it's changed with `AddOutput` or `ChangeVariable`, this PR fixes it.
> Allow dynamic updating of teleport destinations

- mp/src/game/server/momentum/mom_lobby_system.cpp
- mp/src/game/server/momentum/mom_lobby_system.h
Previously to partially address #237, I added code (#1163) that immediately removes/spawns ghosts when a player is blocked/unblocked from steam. This PR changes that code to use the `PersonaStateChange_t` callback from steam instead of checking in every packet.
> Use steam callback to update blocked member status

- mp/src/game/client/momentum/ui/chat/ChatPanel.cpp
With this, everything from blocked players is now... blocked. The only exception is them joining your lobby which I believe isn't possible to prevent.
Closes #237
> Don't show typing status of blocked users

- mp/src/game/shared/momentum/mom_gamemovement.cpp
- mp/src/game/shared/momentum/mom_gamemovement.h
Previously the RNGFix code was ifdef'd out because it caused issues. This PR moves the code under `sv_rngfix_enable`.
Closes one of the cards for 0.8.7
> Move RNGFix code under a convar

- mp/game/momentum/momentum.fgd
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_triggers.cpp
- mp/src/game/server/momentum/mom_triggers.h
- mp/src/utils/zonmaker/zonmaker.cpp
Closes #313 
- Does a slight refactoring of the start zone trigger code
- Adds a remote destination to the start zone trigger, much like teleport triggers.
- destination is teleported to if there is no start mark. (start mark > tele dest > middle of zone teleport)
- Updates zonmaker with the change
Opted not to add the base zone trigger as it would show up for end & checkpoint zones.
Would it be a good idea to add this to stage zones as well?
> Allow teleport destinations as restart points for start zones
