- mp/src/creategameprojects.bat
- mp/src/creategameprojects.ps1
- mp/src/sln_fix.txt
Fixed some .vcproj generation to avoid errors, updated ps1 file, and fixed sln_fix.txt
> VPC update and fixes

- mp/game/momentum/particles/particles_manifest.txt
- mp/src/game/server/momentum/mapzones.cpp
Fixes assertions found upon game boot and map load
> Fix assertions

- .gitignore
- CONTRIBUTING.md
- mp/game/momentum/scripts/kb_act.lst
- mp/src/game/client/momentum/ui/MomentumSettingsDialog.cpp
- mp/src/game/client/momentum/ui/VersionWarnPanel.cpp
Finals weeks and this is what I have time for. Ay.
> Keybinds & grammar

- mp/src/game/client/hl2/hud_credits.cpp
- mp/src/game/client/momentum/clientmode_mom_normal.cpp
Most meaningless, stupid PR ever made. But ey, it's done now! One thing less left to do.
I wish I had time to do more stuff tho :(
> Allows credits fastforward (ATTACK2) and hides the crosshair when rolling credits

- mp/src/game/client/client_momentum.vpc
- mp/src/game/server/server_momentum.vpc
- mp/src/game/shared/momentum/util/jsontokv.cpp
- mp/src/game/shared/momentum/util/jsontokv.h
Please test it before merging it. I'm confident but not 100%
> Jsontokv wip

- mp/src/game/server/momentum/mom_timer.cpp
- mp/src/game/server/momentum/mom_triggers.h
- mp/src/game/shared/momentum/util/mom_util.cpp
Implements mom_stage_tele for mappers. Teleports the player to the desired stage (stopping the timer), stage 1 being the first found starting trigger (and respcting mom_satrt_mark)
IDEA: Make it only available in developer level > 0?
> Mom stage tele

- mp/src/game/client/momentum/ui/HUD/hud_comparisons.cpp
- mp/src/game/client/momentum/ui/HUD/hud_mapfinished.cpp
- mp/src/game/server/momentum/mom_player.cpp
This PR references #173 
Forgot to update convar refs
> Updated fixed convar refs

- mp/src/game/client/momentum/mom_map_cache.cpp
- mp/src/game/server/momentum/mom_timer.cpp
- mp/src/game/server/momentum/tickset.cpp
- mp/src/game/shared/momentum/mom_gamerules.cpp
same changes as last time basically but this time for bugfix and qol branch
also spaces instead of tabs now
> added rudimentary tricksurf support again

- .circleci/config.yml
- .travis.yml
- mp/src/game/client/clientmode_shared.cpp
- mp/src/game/client/momentum/mom_map_cache.cpp
- mp/src/game/shared/momentum/mom_gamerules.cpp
- mp/src/tier1/strtools.cpp
> Bugfix #220

- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_timer.h
Pull Request for https://github.com/momentum-mod/game/issues/273
> Add mom_eyetele command to teleport the player to where they are looking

- mp/src/game/shared/momentum/mom_gamemovement.cpp
> Don't clip player view offset in noclip mode

- CONTRIBUTING.md
The link led me to a blank page, the new link will navigate to website correctly
> Update Link to contributors

- mp/src/game/client/momentum/ui/HUD/hud_speedometer.cpp
- mp/src/game/shared/momentum/util/mom_util.h
> Fix negative values being handled incorrectly for speedometer energy

- mp/src/game/shared/gamemovement.cpp
- mp/src/game/shared/shareddefs.h
Change duck speed from 0.4 seconds to 0.2 in rocket jump gamemode. (#347)
> Change duck speed in RJ gamemode

- mp/src/game/shared/momentum/mom_gamemovement.cpp
> Add ctaps to rocketjump

- mp/src/game/server/momentum/mom_player.cpp
Fixes rockets not giving as much speed as they should when rocketjumping in water (#347).
> Fix rocket damage scaling in water

- mp/game/momentum/momentum.fgd
- mp/src/game/server/momentum/mom_triggers.cpp
- mp/src/game/server/momentum/mom_triggers.h
- mp/src/game/shared/momentum/mom_rocket.cpp
- mp/src/game/shared/momentum/mom_rocket.h
- mp/src/game/shared/momentum/weapon/weapon_mom_rocketlauncher.cpp
Added the `func_nogrenades` entity (#347 )
Also fixed rockets firing into the wall
> Add func_nogrenades and fix rocket spawning issues

- mp/src/game/client/momentum/ui/HUD/hud_versioninfo.cpp
- mp/src/public/tier1/ilocalize.h
> Add Mapping Mode indicator to versioninfo HUD element

- mp/src/game/shared/momentum/mom_gamemovement.cpp
The previous version would just set the ground entity no matter the result of ClipVelocity, meaning it would also set your vertical velocity to zero, resulting in the player having less than NON_JUMP_VELOCITY and therefore stopping on the ramp the next tick. This version checks if the vertical velocity would be above NON_JUMP_VELOCITY and will then not set the ground entity.
> Make the slopebug fix better

- mp/src/game/shared/momentum/mom_gamerules.cpp
- mp/src/game/shared/momentum/mom_gamerules.h
- mp/src/game/shared/momentum/mom_rocket.cpp
> Fix rocket radius

- mp/src/game/server/momentum/mom_timer.cpp
> Don't re-stop timer if it isn't running

- mp/src/game/client/momentum/ui/leaderboards/LeaderboardsTimes.cpp
> Fix leaderboard outline not resetting

- mp/src/game/server/momentum/mom_lobby_system.cpp
> Fix timer starting when teleporting to lobby member

- mp/src/game/shared/momentum/mom_player_shared.cpp
Fixes paint not working on surfaces covered by water closes #429
> Fix paint getting blocked by water

- mp/src/game/server/momentum/mapzones_build.cpp
> Handle negative heights when building zones

- mp/src/game/server/momentum/mom_player.cpp
Hopefully closes #423 
I think i did alright, with some corrections by mantas and slidybat
> Fix Start Mark for multiple Start Zones

- mp/src/game/server/client.cpp
> Block 'give' command when in spectator mode

- mp/src/game/shared/momentum/mom_gamemovement.cpp
Fixed mix-up of duck and unduck times for the smooth unduck and removed setting m_bDucking in c-tap implementation which caused a visually instant unduck (also removed m_flDucktime that got set twice). Also added a smooth duck transition when cancelling an unduck.
> Fix smooth unduck and add smooth duck

- mp/src/game/shared/momentum/mom_system_gamemode.cpp
- mp/src/game/shared/momentum/mom_system_gamemode.h
Adds ExecGameModeCfg() to run the CFG via a client command
First attempt at figuring out class inheritance and such with much assistance from Gocnak and bonjorno7
Closes #441
> Add gamemode specific cfg support

- mp/game/momentum/resource/ui/mapselector/DialogMapSelector.res
- mp/src/game/client/momentum/ui/MapSelection/MapSelectorDialog.cpp
Changed position to empty space.
Changed size to fit space.
Removed hardcoded SetSize in MapSelectorDialog.cpp
Added wide/tall parameters to DialogMapSelector.res
> MapSelector Size/Position Updated

- mp/src/game/client/momentum/clientmode_mom_normal.cpp
> Enforce disabled buttons in non-overlapping keys logic

- mp/game/momentum/scripts/weapon_momentum_shotgun.txt
- mp/src/game/shared/momentum/fx_mom_shared.cpp
- mp/src/game/shared/momentum/fx_mom_shared.h
- mp/src/game/shared/momentum/weapon/weapon_mom_shotgun.cpp
Add cvar to toggle TF2's style of fixed weapon spread, on by default.
I hope I've done the pull request properly this time, my branch should be all cleaned up
> Add fixed weapon spread

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement-request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Adds issue templates and a pull request template to help formalize future issues / PRs made for this repo.
> Add Issue and PR Templates

- .gitignore
Add `mp/game/momentum/custom` to .gitignore
Closes no issue cause there wasn't one but trust me it's important
It's one line so there's not much description I can come up with
- [no] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [no] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
Yes
> Add custom folder to gitignore

- .gitignore
- mp/game/bin/base.fgd
- mp/game/momentum/momentum.fgd
Now it can be directly modified if there are any entity changes or additions, save for momentum entities which go in momentum.fgd
Closes #503
> Add base.fgd to the game's root bin folder

- mp/src/game/client/momentum/clientmode_mom_normal.cpp
- mp/src/game/client/momentum/ui/HUD/hud_mapfinished.cpp
- mp/src/game/client/momentum/ui/HUD/hud_speedometer.cpp
- mp/src/game/client/momentum/ui/spectate/mom_replayui.cpp
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/momentum/mom_replay_entity.cpp
- mp/src/game/server/momentum/mom_replay_entity.h
- mp/src/game/shared/momentum/mom_gamemovement.cpp
Made some fixes to improve replay viewing experience:
Fixed replay ghost's interpolated velocity calculation.
Fixed map finished panel not able to unhide cursor after a replay.
Made other small fixes.
> Replay viewing fixes

- mp/src/game/shared/physics_shared.cpp
Closes #467 
Really basic check of a SHA1 hash of the files, just meant to deter simple file modification, not anything impressive or long-term.
> Protect surfaceproperties files

- mp/src/game/client/momentum/ui/controls/ImageGallery.cpp
- mp/src/game/client/momentum/ui/controls/ImageGallery.h
Closes #506
Update the arrows positions on gallery resize.
> Update arrows on gallery resize

- mp/src/game/client/c_baseentity.h
Closes #564 
These asserts are commented out for the GetAbsOrigin and GetAbsAngles methods, something that Valve ended up doing (long before momentum was a thing), so it seems fitting to just comment these ones out as well for now.
> Fix Pupil Proxy assert

- mp/src/game/server/momentum/mom_online_ghost.cpp
Self explanatory, makes the player make the firing noise for the rocket launcher like it does for the sticky launcher.
> Make players emit rocket launcher firing sound online

- mp/src/game/client/momentum/ui/HUD/hud_speedometer.cpp
Simply moved the code in the `Paint()` method to `OnThink()`. Got rid of the `Paint()` override.
In doing this however, the `OnThink` method is way too large. I am planning on tackling this in another PR but can do that here if you wish.
> Fixed dots on speedometer numbers

- mp/game/momentum/cfg/valve.rc
- mp/src/game/server/gameinterface.cpp
> valve.rc cleanup

- mp/src/game/client/in_mouse.cpp
> Disable mouse acceleration by default

- .github/workflows/CI.yml
Related: #634
Example run: https://github.com/Margen67/game/actions/runs/93042036
> Add GitHub Actions CI for Windows

- mp/game/momentum/resource/ConsoleScheme.res
- mp/game/momentum/resource/SourceScheme.res
- mp/game/momentum/resource/ui/ConsoleDialog.res
- mp/game/momentum/resource/ui/ConsolePanel.res
- mp/src/game/client/momentum/ui/SettingsPanel/AppearanceSettingsPage.cpp
- mp/src/game/client/momentum/ui/SettingsPanel/AppearanceSettingsPage.h
- mp/src/game/client/momentum/ui/SettingsPanel/ComparisonsSettingsPage.cpp
- mp/src/gameui/BasePanel.cpp
- mp/src/gameui/GameConsoleDialog.cpp
- mp/src/gameui/GameUI_Interface.cpp
- mp/src/public/vgui_controls/Frame.h
- mp/src/public/vgui_controls/consoledialog.h
- mp/src/vgui2/vgui_controls/Frame.cpp
- mp/src/vgui2/vgui_controls/Label.cpp
- mp/src/vgui2/vgui_controls/RichText.cpp
- mp/src/vgui2/vgui_controls/ScrollBar.cpp
- mp/src/vgui2/vgui_controls/TextEntry.cpp
- mp/src/vgui2/vgui_controls/consoledialog.cpp
As part of our UI refresh this update, I took to starting with the Console panel as a testbed for the colors and fonts. Designed by Flipybitz with feedback from the team.
New UI color scheme (direction):
Old style:
New style:
Using Bebas for the title, Source Code Pro for the monospace font, we also removed the Submit button and changed scrollbars to, by default, not have buttons. Overall a much cleaner look to apply to the rest of our modals like the map selector and option panel (refactor).
> Update Console Look and Feel to New Design Direction

- mp/src/gameui/OptionsSubVideo.cpp
Uses the new `GetCurrentItem()` method in `ComboBox` to get the value actually shown in the combobox's text entry.
> GameUI Video settings - GetActiveItem -> GetCurrentItem for comboboxes

- mp/src/vgui2/vgui_controls/consoledialog.cpp
Similar to CS:GO, adds a search feature. When the first character of console prompt is a space then a substring search is performed across all cvars rather than autocomplete.
Example:
> Add console search feature

- mp/game/momentum/resource/SourceScheme.res
- mp/game/momentum/scripts/HudAnimations.txt
- mp/src/game/client/momentum/ui/HUD/hud_timer.cpp
Closes #848 
- Adds new Hud Animation to reset timer StatusColor
- Run this animation with HudTimer::Reset()
[Reproduction](https://streamable.com/x2ch4z)
[Fix](https://streamable.com/qo9dcb)
> Reset Timer StatusColor on Player Respawn

- mp/game/momentum/base.fgd
- mp/src/game/client/c_baseentity.cpp
- mp/src/game/client/c_baseentity.h
- mp/src/game/client/viewrender.cpp
- mp/src/game/server/baseentity.h
- mp/src/game/server/gameinterface.cpp
- mp/src/game/server/momentum/mom_system_saveloc.cpp
- mp/src/game/server/momentum/server_events.cpp
- mp/src/game/server/physics.cpp
- mp/src/game/server/physics_main.cpp
- mp/src/game/server/player.cpp
- mp/src/game/server/triggers.cpp
- mp/src/game/server/util.cpp
- mp/src/game/shared/baseentity_shared.cpp
- mp/src/game/shared/gamemovement.cpp
- mp/src/game/shared/momentum/mom_gamemovement.cpp
- mp/src/public/tier1/convar.h
- mp/src/utils/vvis_launcher/vvis_launcher.vpc
Fixes various miscellaneous bugs.
* Fix crash when jumping / interacting with func_train without a weapon
* Increased auto-complete length for commands
* Removed all pause commands
* Removed all references to sv_alternateticks as this caused run submission failure for those on low-end graphics
* Fix a crash when enabling viewport downscaling (closes #928)
> Fix misc bugs

- .github/workflows/CI.yml
Make reg lowercase to be consistent with other commands.
Use output instead of env var for short commit hash.
Prettify robocopy.
Error if upload-artifact finds no files.
> GitHub CI: Minor changes

- mp/game/momentum/materials/dev/glow_downsample.vmt
- mp/game/momentum/materials/dev/halo_add_to_screen.vmt
- mp/src/game/client/c_baseanimating.cpp
- mp/src/game/client/clientmode_shared.cpp
- mp/src/game/client/glow_outline_effect.cpp
- mp/src/game/client/glow_outline_effect.h
- mp/src/game/client/momentum/clientmode_mom_normal.cpp
- mp/src/game/client/momentum/clientmode_mom_normal.h
- mp/src/game/client/viewpostprocess.cpp
- mp/src/game/client/viewpostprocess.h
- mp/src/game/server/baseanimating.cpp
- mp/src/materialsystem/stdshaders/screenspace_general.cpp
This PR changes the entity glow effect to one that gets blurred similar to bloom which makes it look just like that of L4D or CS:GO. It also prevents the glow outline from "splitting out" when the model occupies a relatively small enough region of the screen, as seen here with the old glow:
New glow:
Old glow:
New glow:
> Use an improved glow effect

- mp/src/game/client/c_playerlocaldata.h
- mp/src/game/server/momentum/mom_player.cpp
- mp/src/game/server/playerlocaldata.h
- mp/src/game/shared/gamemovement.cpp
- mp/src/game/shared/gamemovement.h
- mp/src/game/shared/momentum/mom_gamemovement.cpp
- mp/src/game/shared/momentum/mom_gamemovement.h
- mp/src/game/shared/momentum/mom_system_gamemode.cpp
- mp/src/game/shared/momentum/mom_system_gamemode.h
- mp/src/game/shared/movevars_shared.cpp
- mp/src/game/shared/shareddefs.h
Addresses some of #868 
This PR just adds the work Fzzy did a while ago to the main momentum repo so that other tinkerers and coders can also mess around with it while we focus on core game features for 0.8.7 and 0.9.0.
Thanks again @fzzy2j for the work so far, looking forward to more! 😃
> Add Fzzy's Parkour Code

- mp/src/game/shared/momentum/mom_system_gamemode.cpp
Closes #
Just pushing the basic settings for climb based on SKZ.
> added Climb specific settings based on SKZ

- mp/game/momentum/scripts/credits.txt
Closes N/A
Asked Goc, said it was cool if I made a PR for this
> Add self (ijre) to credits.txt

- mp/game/momentum/resource/modevents.res
- mp/src/game/client/game_controls/SpectatorGUI.cpp
- mp/src/game/client/hltvcamera.cpp
- mp/src/game/client/hltvcamera.h
- mp/src/game/client/hud_chat.cpp
- mp/src/game/client/momentum/clientmode_mom_normal.cpp
- mp/src/game/client/momentum/ui/spectate/mom_spectator_gui.cpp
- mp/src/game/server/momentum/mom_player.cpp
Closes #1088 
Closes #1074 
Closes #1076 
A few minor spectating enhancements & fixes. Figured I'd do this now that there are a decent amount of lobbies to test in.
- Allow roaming mode in spectate. Done like in other source games (first person -> third person -> free roam).
- Allows toggle_jump to change spectate mode and toggle_duck to enable spectator mouse input.
- Enable Spectator HUD mouse input when chat is opened.
- Not too sure about this one as it's doing a dynamic cast. Would have to change the spec hud to use a global instead of being a viewport panel to fix i believe.
https://cdn.discordapp.com/attachments/439686613036171265/770435396726685696/2020-10-26_13-17-18.mp4
> Spectator HUD enhancements

- mp/game/momentum/base.fgd
- mp/src/game/client/c_beamspotlight.cpp
- mp/src/game/client/client_momentum.vpc
- mp/src/game/server/beamspotlight.cpp
- mp/src/game/server/server_momentum.vpc
> Add beam_spotlight entity from ASW

- mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp
- mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.h
- mp/src/game/client/momentum/ui/leaderboards/LeaderboardsTimes.cpp
- mp/src/game/client/momentum/ui/leaderboards/LeaderboardsTimes.h
- mp/src/game/shared/momentum/run/mom_replay_base.h
- mp/src/game/shared/momentum/run/mom_replay_factory.cpp
- mp/src/game/shared/momentum/run/mom_replay_factory.h
Closes #930 
The logic that looks for replay files now dispatches asynchronous file read requests to the filesystem. As soon as the callback is called, the replay is added to the list and the leaderboard gets updated accordingly.
~~NOTE: I'm not really sure if what I'm doing with the raw buffer the filesystem provides causes a memory leak. If I interpret it right, the CUtlBuffer should take ownership of the buffer to free it at some point but if I do that, it blocks and the game freezes for a short while for some reason. I looked at the RAM and even with 153 replays I couldn't find any increase when loading everything repeatedly.~~ Not an issue any more
> Load replay files asynchronously for the leaderboards

- mp/game/momentum/gameinfo.txt
- mp/src/game/shared/momentum/util/mom_util.cpp
- mp/src/utils/common/filesystem_tools.cpp
With support for tools
New flexible mounting system that looks in gameinfo.txt and mounts games from your steam library. Uses new block `mount`, it's on same level as `FileSystem` or `HiddenMaps`
Structure:
```
mount
{
*appid*
{
"head"    "0" // put this at head
"mod_folder"
{
"vpk"    "vpk_name" // mounts file: GameDir\mod_folder\vpk_name.vpk
"dir"    "dir_inside" // mounts folder: GameDir\mod_folder\dir_inside
}
}
}
```
Example usage, will mount tf2:
```
mount
{
440
{
"tf"
{
"vpk"   "tf2_misc_dir"
"vpk"   "tf2_sound_misc_dir"
"vpk"   "tf2_sound_vo_english_dir"
"vpk"   "tf2_textures_dir"
}
}
}
```
> New steam game mounting system
